from random import randrange as r
from time import sleep as ts
import os
 
ascii_art = "lllllllllllllllllllllllllllooooooodddddxxxxkkO00KXNX0kk0x:;;,.......'''''......,dOOOOOOOOOOOOOOOkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxddddddddddddddddddooooooooooooooooooooooooooool;''.....,d0KXNNNXXXXXXXKKKKK00o'..    .,,;;:cccllllloollllloolloddxkkOO0KXNNNNNNNNNWWXKKKXXXXXXXXNXXKOdlc;,'.................." \
"llllllllllllllllllllllllllllloooooooooddddxxxkkkkOOOkxodkxo:;'......'''''.......;oxxkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxdddddddddddddddddddddddooooooooooooooooooooooooooooooooocccc:;,.cXMMMMMMMMMMMMWWNNNNXk'        ..,,',;:cccxOkxxxxxkkkkOO000KKKXXNNNNNWWMWWWXxc::cccllllolooc::;,,'..';,,'',,,,'''',,''" \
"lccccllllllllllllllllllllllllllllooooooooddddddddxxddxxdloxxo,''..''',::'...     .;odddddddxxxxxxxxxxdddddddddddddddddddddddddddddddddooooooooooooooooooooooooooooooooooooool:;;;;,,':0WWWWWWWWWWWNNNXXXNXd. .         ..';:::lOKxllloooodddxxxkkkOO00KKXXNWMMWXxc;;;;::cccclclodl:;,,',:d00dlolllllllllllll" \
"ccccccccccccccclllllllllllllllllllllloooooooooodooooooddxoclxxc,''',,:odl,...      'looooodddddddddddddddddddddddddddddddoooooooooooooooooooooooooooooooooooooooooooooooooodoc:c:.  .dKKKKK000OOOOOkkxxkkl. ........  ..,:c:;dK0dclloooddxxxkkOOO00KKXXNWWWMWXkl:::cccllooodxxOOkxl:;cd0NN0dlccccccc::::::::" \
"cccccccccccccccccccccccllllllllllllllllllllloooooooololloxxkxo:'..',;:cloo:'...     .:llllooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodkkkkd'..,loloooooollllllcc:::'.............,cl::xKklllloodddxxkkOOO0KKXNNWWMMMWNOdllcllloodxxO0XXNWN0OxxOXNKkocc:::::::::::::;;;" \
"ccccccccccccccccccccccccccccccccccllllllllllllllllllllllllox00d,....',;clool;...     .,:ccccccccclllllllloooooooooooooooolooollllooooooooooooooooooooooooooooooooooooooooodkOkOOl.':loodxxxxxxxxxxkkxxdol;......,,;;,.'clcck0kdddxxkkOO000KKXXXNNNWMMMMMMWKkddooooddxkOKXWWMMMMMWWNWN0xollcc::::::::::::::::" \
"ccccccccccccccccccccccccccccccccccccllcclllllllllllllllllllclxK0o'....';:clol:'...              ..:lllllllllllllllllllllllllllllooooooooooooooddddoooododddddddxxxxxxxxxkkkOO00x,..'dXWWMMMMMMMMMMMMMMMWXOdoc:;cxkOOx,,loodxxxkkkkOOO0XNNWWMMMMMMMMMMMMMMWNXXK0OOOO0KNWMMMMMMMMMMWXOxoollccc::::::::::::::;;" \
"cccccccccccccccccccccccccccccccccccccccccccllcccclllcccccccccclx00:. ...';:clllc;,.               .;ccllllllllllllllllllllllllllooooooooooooddddxxdl:clccodxxxxxkkkkkkkOOOOO000xc:,.'dKKXNWWMMMMMMMMMMMMMMWNK0KNWMMMNkxkOOOOOO0KKXXKOKNWWMMMMMMMMMMMMMMWWNXXKK000KNWMMMMMMMMMMMWX0xdoolccc::::::::::::::::::" \
"cccccccccccccccccccccccccccccccccccc::::::::::::::::::::::::::::cdl.    ..,;cloodo:,.              .;clllllllllllllllllllllllllooooooooooooddddxxdolcccccccoddxkxxkkkkOOOOO00Kx,...d0c...';cloxkOO0000KK0KKKKKKKKKKKK00000Oxdk0OOOO0O000KKKKKXXXXXXXXK0OOOOOOO0XNWMMMMMMMMMMWNX0kxdollccc:::::::::::::::::::" \
";,,,,,,,,,,,,,,,;;::clc:;'..................................  ..          ..;:cldxdo:.              .,clcllllllllllllllllllllllloooooooodxxxdooooll::;::c:;;:cloddoxkkkkkOO0KOc.. .od.       .............,c:,'.............,:'..............''''',;;;::coxkOKNWMMMMMMMMMMWNKOkxdollccccc:::::::::::::::::;;" \
"l;.............''',,;;:cc:;'.                                              ..';clodkxl,.              ,cccllllllllllllllllllllllllooooddxxddollcclllc;,,;,''',;;;:::codxxxxOKd'.'.','...........................................           ........',;:loxOXNWMMMMMMMMMWNX0Oxdoolllcccc::::::::::::::::::;;;" \
"0Oo;'.....'''''''',,,,,;;:::,..............................................  ..,:cldxko:.              'cccccllllllllllllllllllllllooddxxdoolc::::ll:;'''''..',',,,''';:cccodc;:c::,'''''''''''''''''''''''''''....................... .  ........',:cok0XWMMMMMMMMMWWXKOkxdoolllcccc:::::::::::::::;;;;;;;;" \
"cll:::;;;;;;;;;::::::::::::::;;;;::::::::::::::::::::::::::::cccccccccclclxo'  ..;:codxdc'.             ':ccclllllllllllllllllllllloddxddlc::::;,,;;,''''.......',,....',::;::::clol:'.'''''''''''''''''''''''''...................   ...........';cokKNWMMMMMMMMWWXKOkxddolllccccc::::::::::::::;;;;;;;;;;;" \
";::cccccccccccccccccccccccccccccccccccccccccccccccccc::::c:::cc::ccccccccclkOo.  .';clodxo;.             .:ccccccclccclllllllllllllodddoc:,,,;,'''','...'................',;;;:::cclo:'.........................................................';cx0NMMMMMWMMMWNKOkxddollllcccccc:::::::::;;:;;;;;;;;;;;;;;" \
"'',;;:cclcccccccccccccccccccccccccccccccccccccccccccc:ccccc::::::::::::::c:cokOc. ..,:cldxdl,.            ..............'''';::cclodolll:,,,,,..'........'..''..............';;:clodoooc,',''...'',,;;;;;;;;;;;,''''''......''...............'',;ckXWMMWNXK0KKOxdlllc:::::::::::::lc,'''''''''.............." \
",,''''',;:clllllllclllccccccccccccccccccccccccccccccccccccc::c:::::::ccc:::::coOk:. ..,:lodxo:'.                       ......;;;lodol:::,,;''''......  ......''..............'',clllodxdc::::;,,,;;::::::::::::;;;;,,,,''''''''.............';,:x0XNXXKOxdolcc:;,'',,,,,;;;;;::cccoc..................      " \
";,,''''...',;:cllllllllllcclccccccccccccccccccccccccccccccccccccccccccccc::::::cokx;. .';cldddl;.       .   .         ......':clol::;,,;,,'....'...     .....................'',;;:lldkOO0Oxoolcccloooooooooooolcccc:c:::;;;;;,,,''''.......,dk0Odllllllcc:;,,'....,;;;;;;;;::ccccol.....................   " \
"c:;,,,''......',;cllllllllllllllllllllllcccccccccccccccccccccccccccccccccccccccc:cdkd,. .,:coddoc.                    .'',;;;cooc,,,,'.''...........    ..........   .........',,,,:lookNWNXKXXKKKXXXXXXXXXXXXXXXXXXKKKKKKKK0000000000OOkkkxk0Okxxdddddddl;''''....,::;;;;::::ccccdc................        " \
"lcc:;;,''.........',;:clllllllllllllllllllllllccllccccccccccccccccccccccccccccccccccdko'...,:loddl;.                  ..';:::cll;..'...............................   ........''',,;cccdXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0WMMMMWWNNXXXKK0OO0OOOOOkxo:,....... .;::;;::::::::::o:..........              " \
"dollc:;;,''.......... .,;:llllllllllllllllllllllllllllccccccccccccccccccccccccccccccclxko. .';clool;........... ...... ..;c:,,::,...................................  .........'',,;;;cxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0XWWWWNNXXKKKK0000OOOOkoc,............;::::::;;::::::o:..........              " \
"K0kxdolc:;,'.........    .';ccllllllllllllllllllllllllllllllcccccccccccccccccccccccccccldxl...,:clc::,.... .. .    .....';;,,,'''...................................   ........''',,,,;;cdkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNXXXKKKK000OOOOkoc;''',,,''''....,:::::;;;;;::::cdc...........             " \
"MWWNX0kxol:;,'.......   ..',,:ccloooloolllllllllllllllllllllllllllllccccccccccccccccccccclxxc..,,;;cl:..'...        ...',;,'''...............................................''''''''''..';l0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNXXKKKK0000OOOkdl;'....',,,,''''...,:::;;;;;:::ccclxc.............  ...      " \
"MMMMMWWXKOdc;,''...'.....,,;:coxO00Oxdooooolllllllllllllllllllllllllllllllccllllccccccccccclxxc;;:ccc:;;;,...   .. .'',;;,,,''.......'..''..........''...',............,;::c::;,;;,,,'...',l0NNWMMMMMMMMMMMMMMMMWWWWWWWWWNNNXXKKK0000OOOkkkdoc:,''...';;;;;;;;;,...:::::;;::cccllokc.............. . .      " \
"KXNWMMMMMWXkc;,''.''''''',;codxkkkxxxddooooooooolllllllllllllllllllllllllllllllllllllllllccccldxoc:c:cccc:.........,:c::;;;,'''.',;;;;,,,,'''''''',,;,''.',,...'''..',;:lllllc:cccclll:,...,coodkKNWWNXXXXKKK00Okxxxollllccodddoooooollllllc:;'''.''.;lllllloooc,';:c::::::ccllllokc..................      " \
"dodk0KXNNNN0xol:;,'',,,,,'........'''',,,,;:cllooooooooooollllllllllllllllllllllllllllllllllllloxxoloooollc:,...';cllc::;;;,'',;ldxxddllllccc::cc::cc:;;;;;;:;;:::;,;:cllooooloxxxxxxxkdc'.,;;,,,:dKWWWNNNNNXXXKKk:;cc:;;lllkOOkkkkkkkxddxkkocl;''';,lkxxxkxxxxd:;:ccccc:::cllooldkc.............. .        " \
"l;,codxxkkxolccc:;,,,,,,,,,''.................';::::::::::;;;;;;;;;;;;:::::;;;;;;;;;;;;;;;,,,,;,,;',odooooo;.:'.,;odl:;,,,,'';ok000000OkkkxdddxddoloddooclllloodddolloooooodxxkkkkkkkkO0Od:;:;,'.,:o0WMMMMWMMMMWXOxxxOOkk000KKKKKKKK00OkOOxdlol;,..';dkkkkkkkkkd,':llcccc:clllooldk:.............. .        " \
"l'.,looddxxoc;;,,',,;;;;;;;::;,,............................................................... .. .ldodoooc;;'..;dl;;,,,,,;o0XNNWWNNNNX00OkkOOOkxxkkxddddxxxxkOOOxdxOOkkxkkkkOkOOOOOOOO0Odc:;,'.';cdKWMMMMMMMMW00NNNWWKk0XXKXXXKKKKKK00Oddkkl,..';;;dOOOOOOkkko;,:llcccccclllooldk:.'.............. .      " \
"l..'coddxxxdlc:::;;:::::::cccc;:,.,;,.....,;;;;;;;;;;;:;,,'.......',;::::::;,',;;'.... .'''..:, . .:xxxxxdxxoc,,cdo;,,'',,lONNWWWMMMMWWWNK0OO0000000000OOOOOO00KXK0kO0XXK00OOOOOO0OOOO0OOOOdc;'...,:oKWMMMMMWXKOkOOOkkkxod0XNNXXXXXXKKKKOxkdlc:,;;,':xOOOOOOOkOx;.;llccccccloooooxk:.'.'.'..........        " \
"o..'lodxxkkdlc::::;,',,,,:clllcc,..:l:'...ldddooddddodxxooc,,:loodxxkkkkkkkxoldkkl;:'.,:c:::okc..'lO0O00Oxc,,:;':dc,..',;dKNNWWMMMMMMMWWNXXKKXXKKKXXXKK000000KKXNNXKKKXXXKK00OOOOOOOO0000OOkd:'...';oXMMMMMMNK00OO0000000OOKXXXXXXXXXXKKKkl;;ll;':llokOOOOOOOOOd'.:ollcccclloooooxk:.'''.''.........        " \
"d'.'oxxkkOOxolc:::,.    .:loooll;..;ll,...lxxdddxxxxddxkdc;:clooooodOOOOOOOkxddOOolc::::;,;,;dl',oO000000x;..':coo:..';:dKXNWWWWMMMMMMWWNNNNNXXXXXNNNXXK0KKKKKKXNNNNXXNNXXKK00OOOOO000000OOkxl,....,:oKWMMMMMMMMMWWWWMWWWNXXNNNNNNNXXXXXKdlkxc:;,;c:oO0OOOOOOOOx,.collllcclooooooxk;...'.'........          " \
"k;.'okkOO00Odoolcl:.    .lddxdool;cloo;'.'okkkkkkkOOkkOOkodxkxc;cold0000000000O00xlcldc:;'..;d0OOO0KKKKKKO:..':ddl;.';:o0KXNNWWWWMMMMMWWWNNNNXXXNNNNNNXXKKXXKKXXNNNNNNNNNXXKK000000000K000Okkd:.....,:xNMMMMMMMMMMMMMMMWWWWWMWWWWNNNNXXXXxloo,.;cc,':k000OOOOO0x,'coolllcclooooolxx;.............. .        " \
"Kc.'dOOO000Oxdoolol.    ;dxxkxdddooc:,';;;dOOkkOOOOkkkkO0OkkkxxOKKdoO00KKKKKKXXKKkc;;cooloolcxKKKXKXXKKKK0c..cdooc,'';cx0KXNNNNWWWMMMMWWWNNNNNNNNNNNNNXXXXXXXXXNNWWWNNWNNNXXKKKKK0000KKK00Okkxl,.....,dNMMMMMMMMMMMMMWWWWWWWWWWNNNNXXXXXKxol::;:c;;:oOOOOkkkkkOxc:loollllllooooooxx,.............  .        " \
"l;.'dOO0000Oxddoodl'...,lccllccc::cc;,colcodxxddodxxdxxkkkxxddO0OkocdxxkkxkkdolllloxkxddxOxlldxk0KKOodO0Okdlc:coc;,,,;lk0KXXNNNNWWWWWWWWNNNNNNNNNNNNNXXXXXXXXXNNNNWWNWWWNNNXXKKKKKKKKKKK00Okkxo;......;kOxdddddddooooollllllllllllllllccc:c:::;;;',;;;;,,,,',:dxc;looolllllooooookx,......'.........        " \
",,,:xOO0000Okddddxdc;,,cc;:ccccccdKNXXXXXXKXXXXXKKXXXXXXXXXXXXNNXX0xoodkxdxkkkxlclddoddxdddolcldxOKkccodoldx0Oxxoc;,,;ok0KXXXXNNNWWWWWNNNNNNNNNNNNNNNXXXXXXXXXNNNNNNNNWWNNNXXXXXKKKKKKKK0Okxkxdc,.....'cc,,,,,,,,,,,,,,,'''',,,;;;:;;:;;;;;,,,,''........',''cxkc;oooolllllooooookx,.....',................." \
"dc,:x000KKK0OxxxkkkkkxxxlcclolcccoOK00KKKKKK000KNXKKKK00KK000KNWNX0kxkO0OkkOKN0xkxdxkxdoxOxdollloOKxdxxxddd;:OKOdc;',:okOKKXXXNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXNNNNNNWWWWNNNXXXXXKKKKKKK0Okkkxdc;'.....:llollllllllllc:;,'',;::cdkkOkkkkkxdolc:,'''.',,;::c;;lkd;;lodolllllooooookd'......'..........'.'...." \
"W0c:xKKKXXXKOkkkkOO00OOOdlllol:::cdxoodxdoloooodkOkkkkkkkkkkkOKK000OOOOOOOO0XNKKKKKKK0xdkOolccc,;x0kOOkOddOkx0Xko:,,,:dkO0KKXXXNNNNNNNNNNNNNXXXXNNNNNXXXXXXXXXXNNNNWWWWWWNNNXXXXXKKK0K000OOkkxdc;'.....,cccxXNWWWWWWNXXO, .;dkOKNWMMMMMMMWWWNNKdcc:::ccccloc:oOo,:oooolllloooooookd'............''...''....." \
"MXdlOXXXNNXKOkkOO0KKKKK0d:loollllodddooodxkO0KKKXXXXXXXXNNNNNNNNNNNNXNNNNNNWWWWWNNNNNNXXNNK0KKKKKKXKKKKO:,;.':odl;,',cdOO00KKXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWNNXXXXXXKKKKK00OOkkkdl;'.....';;'.dNMMMMMMMWW0,  ;xKWWMMMMMMMMMMMMWWNkoolllllooodl:dOo,,cooolllllooooookd'............''.........." \
"MNxlkXXXXNNX0OKNNNWWWNNN0k0KKK0000XXXXXNNWWMMMMMMMMMMMMMMWWMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWMWo;oc:lxkl;'.,cdO000KKKXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWNXXXXXXKKKKK00OOkkkdl,......';:c,;0MMMMMMMWW0,  ;kXWMMMMWMMMMMMMMWWNOdoooooodxxxl:xOoldoooooolloooooookd.............'.. ........" \
"MW0dxKXXNNWNK0KXXXNNNNNN0k0KXWWWWWWWWWWWWWWWMMMMMMWWWWWWWWWWWWWWX0KXXNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMWXOd;'lxKNN0o;'.'cdkO000KKKXXNNNNNNNNNNNWWWWWNNNNNWWWWNNWWWWWWWWWWWWWWWNNNXXXXKKKKKK0OOkkxdl,.......;::::0MMMMMMMNN0, .c0NWMMMMMMMMMMMMMMMNOxdddddxxxxxlckOl:odooolllooooooooko.............'..........." \
"MWKkkXNWWMMWNXNNNNNWNNNNOdOKXNNWWWWNNWWWWWWWMMMMMMWWWWWWWWWWWNNXKO0000KKXNMMMMMMMMMMMMMMMMMMMMMMMMMNd'..   .:ONKx;..':oxO000KKKXXNNNNNNWWNNNWWWNNWWWWNNWWWWWWWWWWWWWWWWWWNNXXXXKKKKKKK000OOkkkxo;.... ..,,,,:xO00K0Odlc;. .c0XNNWMMMMMMMMMMMMMW0kxxxxkkkkkkockOo:coooolllloooooookl...........''''...'......" \
"MWKxkXNWWWWMMWWMMMMMMMWWKkOKXNNWWWWWWWWWWWWMMMMMMMMMWWWNNNNNNNXXKKXKKKXKKNWMMMMMMMMMMMMMMMMMMMMMMMMO:;;:;','.lKN0:..';ldkO000KKXXNNNNNNNNNWWWWWWNNNNNNNNNNNNNNNNNNNXNXXXXKKKK0000000000000OOkkkxc....  .;:,.;dxxkkOkdlcc, .cO00KWMMMMMMMMMMMMMN0kkkkkOOOOOOolOOo:loooolllllloooooxl........ ....'..........." \
"MWKdxKNNWWWWWKOKNXO0WWWWOolodk000KK0KXNNXXXXK0OkkOOOOOOOOOOOOOOOkO0OOK0kOKNXXWMMMMMMMMMMMMMMMMMMMMMXxc:lc:od;lKKOl...,:dkOO00KKXXNNNNXXNNNNNNNNXXXXXXXXXXXXXXXXXXX0000OOOkkxdollooooodxxkOOOOkkxl.......;:;;dNWWWWWNNNNNo .o0KKXWMWWMWWWMMMMMWN0kkkOOOOOOOOooOOklclddolllloooooooxl........ ....'..........." \
"MWKdxKNNWWWNx:o0XxlOWWWNd;:ccloollllokkxddxxl::::oxxxxxxxdddddddddkko::okkdxKWMMMMMMMMMMMMMMMMMMMMMMKdclddxOkxd::c'...;dkOO0KKXXXXKK000000000000000000000000000OOkkxxdlc:;,'.......'',;;;cloxkkko,......;:,c0NWWWWNNNNNXl .oKKKKKKKNWNNNWWNNWNXOOOOO0000000ooO0x;;lddolllloooooooxc........ ....'..........." \
"WNOod0XXNNNKdllcxxkXNNNKd;col:;,;::;oOOxoodxoclccxO0KKKK0OOkdlclcoO0xc:;,cdKWWMMMMMMMMMMMMMMMMMMMMMMNk:';okkdl,,:,....,okO00KKK0kxdolcc::;;;;:clodxxkkkkkkkkkkkxxdoo:;,'..........''''''',,;:oxkx:......cOxckNNWWNNNNNNXl .dXXOc'',dKKXXXXXXXKOOOOOO0000000do00lcxdddolllloooooloxc........ .............';c" \
"ool:lOKKXXXXXK0kOKXXNXXNx:coc;,,;;;:lxOkdodxdodlcdOO00KK00OOkl:::cOXK0xl;cOWWMMMMMMMMMMMMMMMMMMMMMMMMKc.';:dkxdd;.'. ..:xO000Oxdlc;,''.........',;:codddddxxxdddollc;;;,,''........'',,,,,,,,:okko.....'kX0kONNNNNNWWNNXl .xWWk;''.:kk0XXXXXK0kOkkkOO000000dd00o:xxddollllooooooox:........ .......   .;oOXW" \
",,,;lOKKKXXXK000OOkk00KXx;:lc;,''';:cldollodooxl:oxkOOO00OOOxl::;;oxxxxdllkNWMMMMMMMMMMMMMMMMMMMMMNK0Ol...,o0x;,..o:...,dOOkdl:::;,,,;,,,''',,,,;;;:clllooddddollc::;;,'.......''''....',;;,,;lxkk:....,k0o:xXNNNWWWWNXKl .kWW0c,',oxdkKXXXXKOkkxxxkOO00000dd00kcldddolllllooooodx:.......         ..:ONWWNX" \
"Odcclk0KKXXXK0OOkOxlk00Kd'.,::,'..,,.,c;',cooodo;ldxkkkOOkkkxc;,,,:cc:;;,,lKNNNNNNNNNNNNWWNNNNNN0o,...:l::lo:.  .c0d....lOkdc::;;:;;,''.........',;;;:ccloddddolc:;,,'...............'''',;;;:cdkOd,...;ol;,cxOkdl:cc::;. .d0o,,;,,:ooxOKKKK0OkkxdxkOO00000dd00Odloxdllllllllllldx:......         .,xNWNXKK0" \
"MKdlcd0KKXXXKOOOxkxokK00d..,clc;,;;,.,:'.';clool;cdxkkOOOkkkxocccccc:;;;;;:looooooddddddxkdoooc,..    .',,'.     'kk'...cOOoccc::;'...............',,;;:ldk000kdc;,,,,''',c:. .    ''..',;:ccloxOOOo'.':lcc::oxdxocclll;. .'. 'llclc,,lk00K0OkkkddxkOO00000od00Okxdddoollooooolldx;......         .dNWNK0000" \
"MXxooxO0KKXXKOOOkkxok0kOd;:dkdc:::cl::c:ldlloxxdccxOOOO00OOOkxxxxxxxddddddddddddddddddddxxxdo;. ..              'okx:...:O0xlcc:;'...''  .   .:;,'';;:::ok0XNNXOoc;;:;,,;:cc,.....,:c:;;;cllodxkOO0Ol'.:loxdcoO0KXXXXNNx.     :kkkkkl..d0000kkxddddkOOO000Ood0OOOxdddoollllooooodx;.......        :XWNXK0000" \
"MXxooxO0KKKKKOOOOOkdk0kOxloxOdc:;;:c::ldkxllodxdc:okkOOOOOkkkxdddddddddddddddddddddddddodxdkx' ..   ..         .lo:;:;.'c0Kxdolc;'.':oc.   ..,cc:::cllloxOKXWWNKOxl:;:cccccclooooooddooodxxxxkOOO00Okl'':lxkxdOKXXKKXXXx.    .okkkkko. cO0000OxooodxkOOOO0Old0O00kdddolllllllllldd;. ......      .dWNXKK0OOO" \
"MNkoodO0KKKK0OOOO0OdOKOOxldxxxollcccclddxdlcoddd:;ldxkkkkkkkxddddddddoodddddooodddddddoodxooc. ..              ':lccxo,,oKKOkxdolloooool::cccllclodddddxOKXNWWWXKOxolcllooooooollloooodxOO0OOO00000OOx:.,:oxkdo0NXXXXXKl.    'dkkkkd,  ,O000KKOoloodxkOOO0kld0OO0kddddddddolllllod,......        ,0WNXKK0OOO" \
"MNkocoO00KKK0OOOO0kdO0xxdclolc::llolccllollodddd:;loxkkkkkkkkxxxxxxxxxxxdddddddddddddddddxxo; ..               .'llo00l:kXK0OOOOOOkkkxxdddoolllloddxkkkk0XNNWWWNK0kxdddxxkkkkkxxxxkkO0KKKKK0000000OOkkl,,:oxko,xNXNWWNk.     ;xkkkko.  'x0O0KXOolllodxkOO0kld0kkkxddxKNNWNklllllod,.....         lNNNXKK0Okk" \
"MNOocoO00KKKK0OOOOkdxOkkxodooololc::;:loolodddoo::lodxkkkkkkxxxxdddxxdddddddddddddddddddddoo:...              ..'lodOxccOXK0000KK00OkxxddoooddxkkOOkkkkk0XWWWMWNK0OOkxkkkO00KKKKKXXXXXXKXXKKK00000kkkxl:ldk0Oc.'ccccc:'     .lkkkkkl.  .dOO0KKklclllodxkkOkcd0dccoddxXMMMWkcllccoo,....         .xWNXXK0Okxx" \
"WNkocoO00KKK00OOOOkdxKkxxoododkxlccldxxold0Kxc:cokkxdxOOOOkdodlldxdddddddddddddddddddddddxxdc..'              .,.;dxxl;c0K00000KKXXXKK000000000000OOOOOOKXWWWWWNXK00OkkkkO00KXXXXXXXXXKKXXXKK0000OOkkxl:d0K0x;..'''''..     :xkkkkko.  'x00KKKklcclloodxkOxcd0x;,codkXWWMNkcclccoo' ...         ,OK0KK0Okxdl" \
"ddllcoO0000000kOOOOdxOdoo;;cloxddoodkOl,:0MWOcco0X0xdkOkxxxoco:;dxdddddddddddddooddddddddxxd; ..              '; .okxl;lO00000KKXXXXXXXXKKKK00KKK0OOOO00XNWMWWWNXKK0OkkkO00KXXXXXXXXXKKXXXKKK0000OOkxdc;xX0o:. ,xOkkxc.    .okxkxxxd;  ,k000KKklcclloodxkOxcd0OdododkKNWMNxcclccoo'  .          .;oxxxdooolc" \
";;:cclkOkkkkkkkkOkxodOdoo;;ccc::::cldxl,:0MW0oloOX0kdxkxdddo:l:;oxooodddddoddddoooddddddddodc'..    ..  ...   ;;  ,xxoclk0O00KKKXXXXXXXKKKKKKKKKKK0OO00KXNWWWWWNXK00OkxxkO0KXXXXNNNNXXXXXXXKKK000OOkxdc;o0xl,  .oOkko;,.. .:xxxxxxxo:. 'k000KKxcccclooddxkdcd0OOxoodkKNWMNxcllccol. ..           .ckxdooollc" \
",;cccclllccclloxxddllxllo;',,,'.':oooxo;:0MWKdllOX0kdddollolclc;ldoddoooooooddooooooooooodk0xl'     ..   ..  .;'   cOkkdxOO0000KKKKKKKXXKKKKKKXKXK0OkO0KXNNWWNNNXK000Okxxk0KXXXXNNNXXXXXXXXXKK000Okxddc;lxko.   ckkxc;;;,. ..'''''.    ,x00KKKxc:cclloodxko:dO0Ododdx0XNNKdcccccol. .             ,ddoollccc" \
":,;:ccccccccccclc:ol:;,co,...'...'looxo;:0MWKdllkK0xoooccclllllclooddoodooooooooooooooooodkkdl'     .        ..    .oOKkokO0000KKKKKXXXXXXKKKXKKK00OO000KXXXXXKK00OkkkkkxxkOKKXXXNXXXXXXXXXXKKK0OOkxxdl;lkkc.   ,dkd:,..',.           'x000KKkoccccllooddko:dOOxxxddxk0KK0dcccccol. .  .          .,cc:::;;;" \
"ll;;clcc::::;;;:;,cl;''cl'...... .;lldo;;OMWKdllkK0xooocccloc:clooodddooooooooooooooooooodO0xdl;.            ..     ;kKOdxOO00KKKXXXXXXXXXXXXKKK0OOO00OOOOOOOOkxdolcclodxxkkO0KXXXXXXXXXXXXKKK00Okxxddo:coc.    .okd;...,c'          .l0000Kk:;ccccllooddxo:dOkkOxodxxk0K0dcccccoc. .. ..          ....'lxxd" \
"dxocccccclooolloccll:;,co;''.......;ldd;;OMWKdllkK0xooolloddl:llododddooooooooooooooooooooodolcc:'  .        ..    .l000xok000KKKXXKXXXXXXXXXKKKKKK0Okxolccllcc::;'...,:cxO00O0KKXXXXXXXXXXKK00Okkxxddl:;'      ;xxd:. .:c:.         .d0O00x' .:cccloodddxl:dOkkOxodkOKXX0dcccccoc. ..                 ,0WNX" \
"xdl:;codxxxxxxddl:clcclod:,,'.....';cdd:;kMWKdllkK0xlcccloddlclllooddddooooooooooooooooooo:'......           ..   .ldk00kld0000KKXXKKKXXXXXXKKXXXXX0dc:,...,;;,,,,'...'':kKKKK000KXXXXXXXKKK00Okkkxdddl:'     .;dxdo:. .:cc'   .,.   ,xOO0Oc..'ccccloddddxl:dOOOkdodxOKKX0dccccclc.                    cNWNX" \
"c::c:;;:::::;,,;'.,:;::cl,';;;,,;;:clddc:kWWXkolxK0xl;;;;:cc::lc:cooooooooooooooooooooooool.                     .:dccoxkllkOO0KKKKKKKXXXXXKKXXXNNXKOol:;;;::::;;;,'...'cOKXXXXXKKKKKKKXKK00OOOkkxdoool:.  .;:oxxddl,. .,cc'   .l;   ;kOO0Oc,,;ccclloddddxl:dO00Odooolclllccccccl:. .                 .dWWNX" \
"'';:,'.........',.,:,,:cc,';;;;;;;:clddc:xWWXxlld00xc,''';;,',cc,;lllooooooolooooooooooool;.                    ;:;c::cxd:cdOOO000KKKKKKKKXKKXXXNNNK0kkxlc;;:cccc;,''',:oxO0KKXXXXKK000000OOOkkkxxdlllc;.  ,xkxxxxdc'....';.   :d;   :kOO0O:.;clllllodxxxxl:dO0K0dooollllcccccccl:.                   .dWWWX" \
"  .,,'.    ....,;,:l,';cc'..'''..',ccoo:,dNWXxlcd00x:....,,'.,cc:cllllloooollooooooooooool,.                   .ldol;:cxolclkkkkO0000KKKKKKKKKXNNNXOxlccc:,';:ccc:;;,;:::ldkOO00KK0000OOOOkkkxdddolcccc;.  .:cc::::'...'.     .ll'   ckkOOOl;:clllloddxxxxc:dO0KOdooolccccccccccl:.                   .xWNNX" \
"  .',''.    ...',;ll;'';:'.'''..';clloo:,oNWXxccd00x:....''..'cc:cllllllooolllooollloooooc.                   .,:oc:ox:lolccdkkkkOOO00000000KKKKKK0xo:;,,;,,;:clooodolc::cloooddxxkkOOOkkkxxxdoollcccc:,.  ..                  ..   .okkkOkc..;llcloddxxxxc:xk0KOdooolcccccccc:cl;.                   .OWNXK" \
"  ..''..       .;:cl;'';:'.'''..',:lllo:,oXMXxccd0Ox:.....'..'::;;clllllloolllllllllloooo:.                  .,,:olccl;lollcloxkkkkkOOOOOO000000Oxdoc;;;;cclddddxO000Okxollc:::::llldxkkxxddoolllcc:cc;'.  .,;;;;;,'.......  .      .,coxkOxooolcclodxxxxxc:xO0KOdlolcccccccccccl;.                   cXWNXK" \
"   ....        .,,:lc;;::..''''..,;cclo:,lXWXklcoOOx:.........::,;clllllllllllllllllllloc,.       .,.        '::cdd:ckooococ;:odxxxxxkkkkkkkxkxdolcc::ccodxxddxkkkxolloooooc:;;,,,;;:codddoollllc::;::,.    ;ddddoolc:::;,.  .'..    ...',:ldkxlcllodxxxxxc:xO00Oololccccccccc:cl;.                  .:dxddl" \
"   .....       ..':c:,:::...'''..,;ccll:,lKMNklcoOOd:.........::,;cllllllllllllllllllllo:.       .;l;        ;xk0OOOK0xxocdl,;cooddxxxxkkxdoccc::::clooolc:;;;:::;'.....'',;:;;,,,,,,;coooollccc;;;;;,'.    .dkkkxxxdoooll;..;c:;.   .,;,'..',clcloodxxxxxc:xkO0kololcccccccccccl,.                  .;lc:;." \
"   .....      ...';:,..,:.........,:ccl:,lKMNklcokOd:.........::,;ccllllllllllllllllllll'..     .cxdl.      .o0OOd;oK0dxocol;,:clooddddxxxoc;;;,;;:cc:;,..............'''.....''',,,,;:llllcc::;;;,,,'';;,'.'x0OOOOkkxddol:'':clc;'....;llccc:::cloddxxxxxc:xkO0kololccccccccc:cc,.                   ,c;;,'" \
"   .....       .,,;c:;,:c'... ....'::clc,cKWNklclkkd:.........;:,;cllllllllllllllllllloc. .     'lloo,      'OKkkl.lK000o:lc,,;:ccloddddxxdc::;,,,,,,,,,;::cccc::clodddoollccccccc::::clllc::::,,,,''....,::cx0KXKKK00Okxdocccccc;,,,;;:looool:,,:cldxxxxxccxkO0kllolccccccccc:cc,                    'lc:;'" \
"   .....      ..,;:lc:::c;........'::clc,c0WNOlclkkdc.....'...;:;;:clllllllllllllllllll;  .     lOOOOo.     .ldkKOclKOdko::,'',:ccccloodddollccclooooooodoodxxddxkkxxdooooooodddddoolcllcc:;;;;,,,,'..''...',:lx0XNNXXK0Okxdolllc:;;:cclooollcc::::::clodx:cxxkOxlllcccccccccc:cc'                    ;oc;,'" \
"   .....      ..',;cc;;;c;.........,;:lc,c0MNOl:lxkdc.....'...;:,,:cllclllllcclllllllll'  .    .ldood:.     .;;:x0OOKOOOc',,',,,;::::cloddololcoxxxxxxdddolllcccc:::::::cccloddddddocccc;;;;;,,''....'',;:;,,;::cd0WWNXK0Okxdoollc:::loodddolcc::::ccccccl;,:cccccllccccccccc::cc'                    'lc;,'" \
"   .....        ...''...'. ........,;:lc,:0WNOlclxkdc....''...;:'.',,,,,,;;,,,;;;;;;,;,.  .    ...'','      .,,,,;;;;;;;'';ccc:;,;:ccccllllllcldxxxxxxxddolcc;;,,,,,,;;;:clodddddoolccc:;,,,,,'.......',;;;::::::clkNWNXK0Okxddoolcccloddddolccc:::cccclll:,,,.';cccccccccccc:::c'                    .::;,." \
"   .....          ..'..............,;:lc;:OWNOlclxkdc....'''..,:'........''...'''''''''.  .    .''''''.     .''',;;;;;;;;:ll:;cc,';:::cc:::::cloddxxxxdddolc:;,''''..',;clooooooolccccc:;,,,''...,;. ..';:::;;;::::cdXWWNX0kxdooolllloddxxdollcccccccccccccccccccccccccc::cc:::::.                    'c:,'." \
"   .....          ..'.........'...',;;ll;;kNNOocldxdc. ..'''..':'...'''.''''''''''''''''.      .';,,,,.     .';;;;;coxxdlc:;;lc;'..';:::;;;;::cccoodddddddoll:;,'''',,:codddolllcc:clc::;,,,'...;::'  ..,;:c:::::::::oKWMWNX0kddoollodxxxxxdolllcccccclllcccccccccccccc::::::::::.             ..... .,:,..." \
"   .....          ..'.........'....,;;ll;,xNN0occdkdc' ..','..':'..''''''''''','',,,,,,,'.      .;;,,,.     .,;:ldkOOOxl:;,;ll;'.....,,',;::cc:::cccldxxxxxxdoolcc::ccoxkkkxoolc::;:::;,,,'...':ccc,.  .';:cc:::;:::::oOXWMMWNKkdoooodxxxxxdooolllllclcc::;:;;;;:ccccc:::::::::::.             .','.. ,:'..." \
"   .....          ..'..............',;ll;,dXN0occdkdl'...','..':'..'''''''''',,,,,,,,,,,,'.     .,;;;'      .cdO0Odlllc:;,;ll:,...  ..'.';:;:cccc:::looooxkkxxxxddoooodxxxxoll:;::;;;'.......;ccccc;. ...,:c::::::::::clclkNWMWNOddoodxxxkxxdoolllllllccc:;;,,,,;:cc:::::::::::::.              ....  ,c,'.." \
"   .....          ..'....'.........',,cl;,oKN0occdkdl'...','..';'..'''''',''',,,,,,,,,,,,,.      .;;;.    .,dKKxlcllc:;,,;llc;'..    :o;,,;:c::::;;::ccccoddddddxdoooooolllcc:,'',,'.......,ccccc::c,. ..,;:c:::;;:::::c:..;kNWWNOddddxxkkxxddoolllllllllcccc::;;:c:::::::::::;:;.                    ,:'..." \
"   ......         ..'....'.......'',,,:l;,l0X0dccdxdl'...','..';,..'''''''''',,,,,,,,,,,,,'      .,;,.   ;kXXx:;clc:;;;,;ll:;'..     :kxoc;,,'','',,,;;;;::lollodolllllc::;;;''..........,:ccccccccc:....';:::::::::::::c;. .cKWMNOddxxxkkkxxdoolllllllllccclllcc:;;::::::::::;:;.                    ';'..." \
"   ......       ....'............'',,,:l;,l0X0d:coxdl,...,,'...;,..''''''''''',,,,,,,,,,,,.      .,;'  ,kNXk:';clc::;;;;clc;'.       :kkkkxo;'......''''',;:c:ccllcc:c:;,'.......   ..,;:ccccccccc:c:,...';:::::::;;;;;::c:,..:KWWN0OOkkkkkxxddoollccccccccccllc:;,'',,;;;;::;;:;.                    .'...." \
"   ..'...       ....'.........'..',;;,;c;'cOX0d::oxdl,...,,'...;,..''''''',::;,,,,,,,,,,,,'.     .,;',xNW0l..;ccc::::;;:ll;'..   .. .:xkkkkkxoc;...........'',,,,,,,,'........   ..';:::ccccccccc:cc:,....;:::::::::;,,;::ccc'.:0NMMMWNNXKK0Okdooolllllccccccccc:,,,'''.'',,;;;;,.                    'c;..." \
"   ..'....     .....,............',;;,;c;'cOX0dc:oxdl,...',,...,,..''''''',;;;,,,,,,,,,,,,..      .:xXMWO;..':cccc:::;:clc,..   ... .:xkkkkkkxxdoc;'..     ...........       ...';;::::cccccccccccc:;,....;:::;;;;;;;;;;;::cc:. ,xXWMMMMMMMMWNX0xollclccccccccc:;;,,,'''.....'''..                    'c;'.." \
"   ..'....    ......,'........'..',;;,;c;':kK0dc:lxdl;....,,...,,..'''''''''',,,,,,,,,,,,.....   .;kWMWk'  .';clcc:::::cl;'..   .....;dxkkkkkxxxdddoc;,,'.....  ............',;::::::cccccccccccccc:;,....,::;;;;;;;,,;;;::::;.  .oKWMMWWWWWMMMMWXOdlccccccccc::;;,,'''''''.......                    .::,'." \
"   ..'...... .......,.........'..',,;,;c:':kK0dc:lddl;....''...,,..''''',,',,,,;;;;;;,,'....''',;:kNMWO'  ..';ccccc::cclc;'.   ..'...'lxxkkkkkxxxxxxdoolllc:;;,,,'''.'.'',;:::::::::cccccccccccc:::;;'...,;;;;;;:;,,,;;;;:;;;'..  .lXWMMWWWMMMWWMMWNKOdlccc:::::;;,,,,,''''''...........              ;doc;'" \
"   ..''.............'.........'.'''',',c:';xK0dc:lddl:'.......,,,..''''',,'',,,;;;;,'....'',;;;;,;xWMK;  ...';:cccc:::clc;'..  ..','..;oxxxxxxxxxxxxxddoollcccccc::;;;;;;;;;:::::ccccccccccccc::::;;,.. .,;;;;;;;;;,,,;;;;,'..;c,'.'dXWMMMMMMMMMMWWMMMWXOdlccc:::;;;;,,,,,''''''...............      .cdllc:" \
"   ..''.......................'.....,',c:';xK0dc:lddl:...''....',.....'''''''',,,,,'',;;;;'......'xWMNo. ...',;ccc::::clc;'......',,...:dxxxxxxxxxxxxxddddollccc:::::;;;;;;;:::ccclllccccccccc:;;;;,.....,;;;;;;;;,',,;;,,,'';lolocl0WWMMMMMMMMMMMMMMMMMMWKOoc::::;;;;,,,,,''''''....................'collc:" \
"    .''.......................'....',,,c:',dK0xc:cddl:....... .',....''..''''',,,,,'''''......':lkXMMMXc....'';ccc::::clc;,'.....';,'...:ddddxxxxxxxxxxxddddollcc::::::::::ccccclllccllccccc::;;;;;,.. .,,;;;;;;;;,',,,,,,;cllloddkXMMMMWWMMMMMMMMMMMMMMMMMMN0xlc;;;;;,,;,,,,,,,,'....................:llcc;" \
"    .'''''....................''...',,,::',dK0xc;cddo:....'.. .,;...'''''',,,,,,,,,,,,,,'.';lxKNMMWWMMW0:..'',;::c::::llc:;,'....';;,....;oddddxxxxxxxxxdddddooolllcccccccccllcllllcccccccc::;;;;;,'. ..,;;;;;;;;;,'',,,;:cllllddxKWMMMWWWMMMMMMMMMMMMMMMMMMMMWX0xc;;;;;,,,,,,,,,''...................,llc:;" \
" ....''''''..................'''''',;,,::''oK0xc;cddl:.........:lc;,''''',,,,,,,,,,,,,,;lx0NWMMMMMWNWWMW0c,,,;::cc:::cllc:;,'.....,;,'.. .,codddddddxxxxxddddoooooolllllccccccccccccccccc::;;;;;;;,.. .';;;;,,;::;,',,;:ccllllodkXWMMMWXNWMMMMMMMMMMMMMMMMMMMMMMMWXkl:;;;;;,,,,,''....................'clc:;" \
".'','''''''...................'''''',,'::''o00xc;cddl:'.......,ccl:,,,,'',,,,,,,,,,,;lxKNWMMMMMMMMWNNWMMWKdccccccc::cllc:::;,'....';;,'.  ..;looddddddddddddooooollllcccccccccccccccccc:::;;;;;;;,.. .',;;;,,;:::;;,,;cccccloodONMMMMXxxXWWMMMMMMMMMMMMMMMMMMMMMMMMMN0d:,,,,,,,,''.....................:lc:;" \
",,,,'''''.....................'''''',,';:''o00xc;:odl:'........,,;,'''''',,,,,,,,;cxKNMMMMMMMMMMMMWNXXNWMMW0dlcclcc:clcc:;;;,,'....,;;,'.  ..':loooddooooooooolllllcccccccccccccccc::::::;;;;;;;,.. .,,,;;,';:::::ccc::ccloookXWMMMWKo:xXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l,,,,,,'''.....................,cc:;" \
"'''''''''.......................'..',,';:''l00xc;:odoc,........'''..'''''',,,,,;lkXWMMMMMMMMMMMMMMMNXKXXWMMWNOdllccccccc:;;;;,''...',,;,'.  ...,clloooooooolllllccccccc::cccc:::::::::::::::;;;,....::,,;,'';::ccllllllllodkKWMMMMNOc;lOXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;,,,,''''.....................:cc:" \
"''....''................''....'''...,,';:,'lO0xc;:odoc,.........''..'''''',,,;lONMMMMMMMMMMMMMMMMMMWXXKKXWMMMWXOlcllllll:;;;;;,,''..',;,,..  ....;:clloooooolllccc::::::::::::::::ccccc::::;;,'.. .:ll;,,,,::cccllllooooxOXWMMMMMNx;;lx0NWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:,,,,'''.....................:lc:" \
".......''.............''''....'''''',,';:,'cO0xc;:odoc,.........'''''''',,,;lONMMMMMMMMMMMMMMMMMMMMWNXKKKXNWMMMWKdcllollcc:;;;,,''...',,,..    ...';cllloooolllcc:::;;;;;;::::::ccclcccc:::;;,....,lol:;;::ccccclllloxOKNWMMMMMMXx::lx0XWWMWWMMMMWWWWWWMMMMMMMMMMMMMMMMMWWW0c,,,'''''..................;odlc" \
"......''''......'''''',,,,'..''''''',,';:'.ck0xc;:odlc,........'''''',,,,;lONMMMMMMMMMMMMMMMMMMMMMMMWNXKKKXNWMMMMXdcloollllc::;,,''''',,,'...   ....,:clooodooollcc:::::::ccccclllllllccc:::,.. .;clolc::ccccccllodk0NWMMMMMMWN0dlldkOKNWWMMMMMWWWWWWWWMMMMMMMMMMMMMMMMMWWWWXo,,''''...''.............'oOkoc" \
"......'''''..'''''',,,,,,,'...'''''','':c'.:xOxc;:odoc;'.''''''',,'',,,:d0NMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKKXXXNWMMWNOollloollcc::;,,''''',,....   ....,:cloddddddoolllllllllllllloooolllccc:,....cOoldol::cc:clok0XNWMMMMMMMWXklldxkO0KXNNWWMMMMWWWWWNWWMMMMMWWMMMMMMMMMMWWWMMXd;,,'''''.............,:dKK0xc" \
".......''''''''',,,;;;;;;;,...'''......cl'.cxOkl;;ldl;'.''''''',,,,,,,,oNMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXXXXKKXKXNWWX0kdlllllllc::;,,,,,,'..''.   ....',codxxxxxdddooooooooodddddddoollllc,....;0NxlddocccldkKNWMMMMMMMMMW0l;;:oxk0KXXXXXWWMMWWWWWWNWWWWWWMMMMMWWWMMMMMMWNWWMMXo,,,'''''...........:ooooooc," \
"......'''''''',,;;;;;;;;;;;'..'........,;..;lol,..''....''',,,,,,,,,,,lKMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWNNX0dlc;;o0NWWNKOxolllcc:;;;;;,,,..,'.... .....,coxxxxxxdddooodddxxxxxxxxdoooool;....,kNXdlxxdoOKNWMMMMMMMMMMWKxc'.,coxOKXNNWNNNNWWMWWWWWWWWWWMMMMMMMMWWMMWWWWWWNNWMMMXo,''''''''........'codoc;::;" \
"......'''''',,,;;;;;;;;;;;;'.............  .......',,;,'''',,,,,,,,,,cKMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWNXOo:c; .:xOKWWWWNKOxol::;;;;;;;',,,..:;. .....'codxddddddddddxxxkkkkkxddodool,... .dNWXdldkkx0WMMMMMMMMWX0xo:,'',cldOKXWWWWWWWWWWWWWWNNNNWWWWMMMMMMMMMWWWWWWWNXWMMMMMXo'''..............'',,'',,." \
"......'',,,;;;;;;;;;;;;;:::,'..............';::;,',;;;,'''',,,,,,,,,c0WMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWMMWWNXOl;cc. ;oloxOKNWWMWNXKOxoc;;;'',::,,coc. ......;lodddddxxdxxxxkkkkkkxxxdddl,... .lKNWXxloxkkOXMMMWNX0kdc::::::::clxOKNWWMMWWNNNWWWWWNXNWWWWMMMMMMMMMWWWNNNNNXXNMMMMMMXo''...................    " \
".....'',,;;,,,,,,;;;;;;;;;;,'...........''',:c:;,,,;;;,''''',,,,,,,c0WMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWMMWWWNX0o:cl;.,olcloxk0KXWWWMMWWX0kxdc:l:,,:dxl.  ... .'cloddxxxxxxxxxxkkkxxxxdo:.... .;0NNK0OxxkkOO00xxdolc:::clooodocclxOKNWWWWWWNNWWWWWWNNWWWWMMMWWMMMMWWWNNNNNXKXWMMMMMMMXl'......................." \
".............''''''''',,,,''''''....'''','',:::;,,,;;,,,'''',,,,,,lKWMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWMMMMWWWNX0xc:l:.,llcoxkxdddxkKXNWWWWWWWOcl:,',okko'....  ..,coodxxxxxxdddxxxxxxdc,......'kXK0000kdllclddc:ccc:cclodkkOOxlcldOKXNNWWWWWNNWWWWNNNWWWWWWWWWWNNNNNNNNNNXKKXWMMMMMMWWKc...................'..." \
"..............''''''',,,,,,,,'''''',,,,,,,,,;::;;;;;;,,,,,,,,,,,,c0MMMMMMMMMMMMMMMMMMMMMMMMMWMMWWWWWWMWWNNNXKkoclc,:oolokkkkxdollodxOKXNWWOlc;';:lodxoc'...   .':lodxxxxdoodddddol;........oXK0KKK00Okdollc:ccc:clodxO0000kllox0KXXNNWWWNNNWWWWWNNWWMMWWWWNXKKKKXNNNNNXKKNMMMMMMMWWW0:..................'..." \
"..............'''',,,,;;;;;,,,'',,,;;;,,,,,,;::;;,;;;;,,,,,,,,,,:OWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWNNNXKOdcll;:ddldkkkkkxdddoolccccoOxlc;;llldooooc....    .':loooooololc:;'.........:OK0KKKXNWWWKkl:cccclldxkO0KKKK0klcok0KXXXNNWNNNNNWWWNNNWWWWWWNXKOO0KXXXNNNXKKNWMMMMMMMWWWWO:'...............'''.." \
".............''',,;;;;;;;;;;,,,;;;;;;;,,,,,,;::;;,;;;,,,,,,,,,,;kWMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWNNNXKOxlll::odldkOOOOOkxxxddol:''cl;,;:clodddoll:......   .';cllolc:'...   ......,x0000KNWWNKkl:clollodkO00KXXXNXKkollxKXNNNNNWWNNNNWWWNNWWWWWWNX0kk0KKKXXXXXKKXWMMMMMMMMMWWMWk;''.................." \
"............'',,;;::::::::;;;;;;;;;;;;,;,,,;;::;;;;;;,,,,,,,,,,oNMMMMMMMMMWMMMMMMWWWWWWMMMMWWWWWWWWWWWWWNXXK0Okoooc:odldO00000OOkxxxxdoc:;;;;cldkOkddddol:.....     ..;cc;'.. ..........;d0000XWWNOdl::cldxxxkO0KKXXNNNNXKOollxKKXXNNNWNNXXXNNWWNWWWWWWNKOk0KKKKKXKKKKKNWWWMMMMMMWWMMMNd,'''''.............." \
".........'',,;;;:::::::::::::::::;;;;;;;;,;;;::;;;;;;,,,,,,,,,lKMMMMMMMMMMMMWWMMWWWWNNWWWWMWWNNNNWWWWWWWNXK0OOkdooccxxoxO000KK00Okkkxxdolc:,;lllodxxdxxddol;.         .'.. ............ck000KNWXOdl::clldkkkO00KKKXNNNNNXKkollx0KKXXNNNXXKKKXNWWNWWMMMWXOkO0KKKXXXK0KKKNWWWWMMMMMMMMWWWXo,''''''''.....'''.." \
"........',,;:::::::::::::ccccc:::::::::;;;;;;;;;;;;;;;,,,,,,,:OWMMMMMMMMMMMWWWWWWWWWNXNNWWWMWNNNNNNWWWWWNXKK0OkxdollkkdxO00KK000OOOOOkkxdlc::clooolloxkxxdddc'.    ..... ............'oO00KXNXOdoc::clddkO0O0KKXXNNNWWWNKKOolokKKXXXXXXXK000KXNNNWWMMWNKOOO0KKKKKK0000XWWWWWMMMMMMMMWWWWKc''''''''.........." \
"......',;;:::::::::::ccccllcccc::::::::;;;;;;;;;;;;;;;,,,,,,,dNMMMMMMMMMMMMWWNNNNNNNNXKXNNWWWWNNNNNNNNNNNXK00OOkdollkOxxO0KKKKK0OOO000OOkdoc:clooddoccloxxddoo;.....    ............'oO0KXNXOxolc:clodxkO000KXXNNNNWWNNXKKOolokKXXNNXXXXK0000KNWWWMMMWX0O00KKKKKK000KKNWWWWWMMMMMWMWWWWWWO;''.''............" \
"...'',;::::::::::cccccllllllccc:::::::::;;;;;;;;;;;;;;,,,,,,lKMMMMMMMMMMMMMMWNNNXNNNXXKKXXNWWWNNNNNNNNNNXXK0OOOkddllkOxxO0KKK000000000OOOkxolccldddddoolcloddddc.        ...........oO0KNXOxol:;:ldxxkkO0KXXXXNNNNWWNNNXK0OoclkKXXXNNNNXK00OO0KNWWMWWNKOO0KKKKKKK000KXWWMWWMMMMMWWMWNNWMMNd'''''............" \
".',,;;::::::::::cccllllllllcc:::::::::::::;::::;;;;;;;,,,,,;kWMMMMMMMMMMMMMMMWNXXXXNNXK0KKXNWWNNNNNXNNXXXKK0OOkxdoclkOxxO0KKKK000OOOOOOOOOkkdlclodddddxxdlcldddo:. ...    .........lk0KKOdol:,:ldxOOOOO0KXNNNNNWNNNNNNXK00Ooclx0KKXNNNNNXK0Okk0KNWWWNKkk0KXXXXKK00K0KNMWWWWMMMMMMMWWNWWMMWKc'''............." \
",,;;;::::cccccccllllooolllcccccc::::::::::;;:::;;;;;;,,,,;;oXMMMMMMMMMMMMMMMMMWXXXXXXXXK00XNWWWNNNNXXNNXXXK0OkxdolcoOkxk00KKK000OOO00OOOOOOOkdollooddddxxxdlclool:................,dO0koddc;:ldkOOOO000KXNNNNNWWNWNNNNXXKK0dccx0KXXNWWWNXK0Okkk0KNNWN0xk0KXXXKK000KKXWMMWWWMMMMMMMWWNWMMWWNO:'''............" \
";;;::::cccccccllloooooolcclllcccc:::::::::::::;;;;;,,,,,,;:kWMMMMMMMMMMMMMMMMMWNXXKXXXXK00KXNWWNNNNXXXNXXX0OxxxdolcoOkxO00KXX000OO0000OO000OOkxollodxxxxxxkxocclol;...............:kkocxx:;:oxk00K00KKKKXNNNNWWWNWWNNNNNXX0dccx0KXNNNWWNXXK0kxkOKXNNXOxk0XNXXXK0OOOKWWWWNNWMMMMMMMWWNWMWWNWNd''''...'......."

 
c = 0
colors = ['\033[97m','\033[96m','\033[95m','\033[94m','\033[93m','\033[92m','\033[91m']
while 1:
    print("\033[1m"+colors[c]+ascii_art)
    c += 1
    if c == len(colors):
        c = 0
    ts(0.1)
    os.system('clear')
