#-*-coding: utf-8-*-

from random import randrange as r
from time import sleep as ts
import os
 
ascii_art = "’’’’;xNMMMMMMMMMMMMMMMWWWNNNXXXXXKKKK00000OOOOOOOkkkkkkkkkxxxxxxxxxxxdddddddoooooooooooooolloollllllllllllo;         .::::::::::::::::::::::::::::::::::::::::;;::::::;;;:;;;:;;;;;;;;;:::::::::::;;:::::::::::::;::;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;,,,,;;;,,;;,,,,,,,,,,,,;;,,,,,,,,,,,,,,,,,,,,," \
"......:xXWMMMMMMMMMMMMMMWWWNNXXXXXKKKK00000OOOOOOOkkkkkkkkxxxxxxxxxxxddddddddddooooooooooooooooooolllllllloo'        .,:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;::;;::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;,,,;,,,;;;;;;;,,,;;;,;;;,;;,;;;,;;,,,,,," \
"'''.....,lONMMMMMMMMMMMMMWWWNNNXXXXKKKK000000OOOOOOkkkkkkkkkxxxxxxxxxxddddddddddddoooooooooooooooooooollllldo.        .;::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;;;;:::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;,,,,," \
";;,,''.....:xKWMMMMMMMMMMWWWNNNNXXXXKKKK000000OOOOOOOkkkkkkkkkkxxxxxxxxddddddddddddddoooooooooooooooooooolloxl.        .,,,,::::;;;;;::clllcc::;;;;:::ccc::::::::cccclllllllcllloooddddoolllllccccccc:::::::::;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,'''''''''',;:cc,..................''''''''''''''''''''''''''''''" \
":;;;,,'''....,ckXWMMMMMMMMWWNNNNXXXXKKKKK000000OOOOOOOOkkkkkkkkxxxxxxxxxxxdddddddddddddddooooooooooooooooooldOc.           .,cc;,''';codxxdodo:,'..,,;cll:;;;;:ccllodxxkkOkxdxkO00KKKKK0Okkxxxddoolllllccccc::;;;;;;;;,,,,,,,,,'''',,,,'''...........';loc'.............    ................................" \
":;,,''''........;o0NMMMMMWWNNNXXXXXXKKKK0000000OOOOOOOOkkkkkkkkxxxxxxxxxxxxxddddddddddddddddoooooooooooooooook0c... ... ....,:;,',;:llooooodxkd:,..',;:llc::ccccllooddxxkkxdodxkkOO00000OOkkkkxxxxdddddooooollcc:::;:::;,,,,,,,,',,,,,,,'''''''''''',col;..................................................." \
"c:,,''............,cxKNWWNNXXXXXKKKKKK000000OOOOOOOOOOkkkkkkkkkxxxxxxxxxxxxxddddddddddddddddoooooooooooooooooo00c'''',,,,'.';;,,;:ccc::::clodxkkl..';;:lolclllllloooddddxxdooodddxxkkOOOOOOOOkkkkkxxxxxxdddddooollccll:,'''''''''''''''''........,:coo;.....               ....                           .." \
"oc;,''.....''''....'';lx0KKKKKKKK000000000OOOOOOOkkkkkkkkkkkkxxxxxxxxxxxxxxdddddddddddddddddooooooooooooooooooxKk'....''...'''',,,;;;,,,;:::cloxx:.';;:ldooooodddddddddddddoooooodxxxkOO00000OOOkkkkkkkkkkxxxxxxdddddl;'.......................';okx;.                                                     ." \
"Okxl;'....',::,'..''''',;ldkOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkxxxxxxxxxxxxdddddddddddddddddddddoooooooooooooooooookKd.........',''',,,;;;;:::c:::ccc:'';:;ldddxxkkkxxddddddddooooooddddxxkOOO0000OOkkkOOOOOOO000KK0O00Oo:,'......................'cxkl.                                                    ...." \
"kkOOOxo;'.',;::;'''',,,,,,;:ldxkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddooooooooooooooooooodOKo',;,,''..':llllooddxkOO00000K0l..',,::::::cc::lddxxxxxxxxxxkkkkkOO00000KKXXXXXXXXkoooodddxxxooddl:,;,,,'''''''...''........;dd:.....................................................'''''" \
"OkkxxkOOkdc;'';;,,,,,,,,;cc:,,:codxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddooooooooooooooooooooooooood0Kl',,,'''..'cooooddxkOO00KKKXXXd...............:dx00dlooddddxxxxxkkkOO000KKXNWMMMXo::::::::::cll:;;oxolollllllccccccccccccccccc::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,," \
"xxxkkkkxkOOd:....'''',,;::ccc:;,,;loddddddddddddddddddddddddddddddddddddddddddddddodddoooooooooooooooooooooooooooxK0l;:::;;,. ,cccllllooodddxxkOOo,,,............:dkK0ocllllloodddxxxkkkOO00KXWMMMNklclcccclllodkOockXOollllcccccc:::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,;;;;;;;;,,;;,,,,,,,," \
"xddddxxkOOOOxc,......',,,;;:::c::;,;:loooooooooddddddoddddddddddddoooodoooooooooooooooooooooooooooooooooooooooooookXKkxxxxxkc..;;;:::::::::cccccc;;:;...........'cdOKklclllooodddxxkkOOO00KXNWMMMW0doooooodxk0XK0Ok0XOollccc:::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,;;,,;;,,,,,,,,,,,,,,,,;" \
"ddddddddddkO0K0xc,.......',,;;::c::;,,;::::;,;;;,;;;:loooooooooooooooooooooooooooooooooooooooooooooooooooooooddddddOKOkkkkkOOl,;:cllllooddddxxdddddo:'.....',,,,;oxk0kdoddddxxkkkO00KKXXXNNWWMMMMNOxxxxxxkOXNWMMWWWNOdollccc::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,,,,,,,,,,,;;::" \
"oooooooooooodxk0K0xc.   .....',;;:::::cc;,'..        .,cllllllllllllllloooooooooooooooooooddddddddddddddddxxxxxxxxxkkkkkkOOOK0c,;ldkO0XNWWWWWWWWMWWNKkkxddooxkOklldxxxxxxxkkkOkOKKXNNWWWMMMMMMMMMWNNNNXXXNWMMMMMMMW0ddollccc:::::::;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;::ccc" \
"lllllllllllllllloxOOc.      ....',;;::loxxoc;'..       .':cllllllllllllllllllooooooooooooooodddddddddddxxxxxxxxxkkkkkkkkOOOO0N0c,;;:cox0NMWWWMMMMMMMMMMMMMWWWMMWKOOO00000K00KK0KNWWWWWWMMMMMMMMMMMMMWNNWWMMMMMMMMWKkdoollcc::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccccc" \
"..'..'''''.........'.           ...',;;:ldxxxo:,..       ..;clllllllllllllllllllllooooooooooooodddddddddxxxxxxxxxkkkkkkkOOOOOKXo.......'o0OdoodxkkOOO00000XNX0000000OOOOO0O0X0OO0OOOOOOOO0000KKKKKK000XWMMMMMMMMWKOxdollccc::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',,;:cllllllcc:" \
"..............                     ...',;:cldkkdl:,..       .,:cclllllllllllllllllllllooooooooooooddddddddxxxxxxxxkkkkkkkOOOO0XK;.......':c,....'''',,,,,,:c:,,,,,'''''''',::'.'.........''',,;;:cloxOXWMMMMMMMWKkxdolllcc:::::::;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;clooooolllcc::" \
"'''''''''''''''''''''''''''''''',.    ...',;:loxkkdc;'..      .';ccccccccllllllllllllllllloooooooooooddddddddxxxxxxxkkkkkkOOOO0Nk,''''',,,,,,,,,,;;;;;;;;;,,,,,,,,,,,,,,,''''''''.........''',,;:clx0NMMMMMMMMN0kxdoolccc:::::::;;;;;;;;;;;;;;;;,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;:looooooooolllccc" \
":cccccccc:::::::cccccccccccccccokOd:.    ...',:cloxxdl:,..       .;:cccccccccllcllllllllllllllloooooooooddddddddxxxxxxkkkkkOOO0KXo,,,,,,;;;;;;;;;;:::::::;;;;;;;;;;;;;;;;,,,,,,,''''''''''''',,;clx0NMMMMMMMWXOxddollccc::::::::;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''',,:cloooddoolllllllll" \
"ccllllccccccccccccccccccccccccccldkOOxc'.  ....';:clodxdl:'..      .,::ccccccccccccccccclllllllllllooooooooooddddddxxxxkkkkOOOO0Xk;'',,,,,,,,,;;;;;;;;;;;;;;;;;;;;,,;,,,,,,,,,,''''''......'',;:ld0WMMMMMMMWKkxdoollccc:::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''',,;:cloooolllccclllooo" \
"llllllccccccccccccccccccccccccccccccoxOOxl;'......,;:codxdoc;'..    .........................,;:::::::::;;,,,,,;;;;;,;;:cclllloodo::;;;;;;;;;;;;:ccccc:cc:::;;::::;;;;;;::::;;;;;,'','.....',,;co0WMMMWWWWXOdoolcc::;;;;;,,,,,;;;;;;;;,'''''''''...................................'',,;:clllllccclllloooddd" \
"lllllllllccccccccccccccccccccccccccccccldkOko:.......,;:lodddlc;'.                            .',,,,;;;,'..............,,',,,,,;::cc:::::ccccccclllllllllllcccclccc:c::cccccc::::;,,,,''''.'',;cxXMMWN0kxdoc:;;,''...........',,;;:ccc,..........                          ........',,;::cccllllllooodddolc;" \
"llllllllllllllllccccccccccccccccccccccccccldkOko:'.....',;cloddol:,..           ...  ..        ..'',,,,''..........'',;:;;;::::cllodollllodooddddxxxxxxxxxxdddddooooolooddoooolllc:;;,,'''''',;oKWX0kdolc:;;,,'''...........',;;;:ccll,..........                          .......',,;:::clllloooddool:,'..." \
"llllllllllllllllllcccccccccccccccccccccccccccloxkkd:'.  ..',:clooooc:'.                        .....'''''..:oodxxxxxocllloodddxkkkOOO0K0KKXKKXXXXXXXNNNNNNXXXXXXXXXXXXXXXXXXXXXXKK000OOOkkkkkOOXWXKOkkkxxddooolllcc,.. .....,;;;:cccll,.........                           ......',;;::cclloodoolc;,........" \
"oolllolllllllllllllllllllllcllcccccccccccccccccccoxkkd:'.  ..';:cloool:,...                        ........:dOKKXXNXOlclodxxkO0KXXNXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNMMMMMMWWWNNXXXKK000OOOkkkxxo:...  ....;::::ccccc'.......                              ....',;;::clloolc:,............." \
"lloooooollllllllllllllllllllllllccccccccccccccccccccldxxdc'.  ..';:cllc::;,.........................'''''''',:clllooolc:lloxOXNWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWMMWWWNNNXXKKKK0000OOOkkkxl,.........';:::::::cc'.......                              ....,;;:cccc:;,...........,coddo" \
",;;:cloooooooooollllllllllllllllllllcccccccccccccccccccloxxdl,.. .',;;;:ll:,..''''....         .........''''..,okOOOO0000KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWNNXXXXKKKK0000OOOOkxo:,'.......'',::::::ccll,.......                             ....';;:;;,'.............',:d000O" \
"'''';cdxOOkxdooooollllllllllllllllllllllclllllcccccccccccclodxdl;...';:cccc;;,;;;;,'...        ....  ...'''....'oO0KKKXXNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNXXXKKK0000OOOOOkdc;,,,,......'';:::::cclol'.......                             ...''''............. ..',;;,,:lc," \
"',,,;cdxkkkdollllooooolllllllllllllllllllllllllllllllllccllcccodxdl;'..,::::::cccc:,................',,,'........coxkkkO00KKXXNNNNWWNNWWWWWNNNXXXXXKKKKKXXNWWWWWMWWWWWWWWWWWWWWWWNNNXXXXK0000OOOOOkkkkxxxxdl:;:;;,'.....,;;:c::ccllodo,..........                          .................... .''''......." \
"',;;,,'.....'''',;::cclllllllllllllllllllllllllllllllllllllllllllldxdo:,;:;;:clllllc:;'..',,',;:lllllllc'.,:,.....',;:cldxxkxodkOxxO0OOOOOkxxxkxxddddddooodxxkkOKX0kOO0XNNNNNXXKK00Okdccc:::;;:odddooooooolllll:,,''',''clllcccclloodo'........   .    ......               .,,,,,,,,,,'''''''.............." \
",,;;;;;;;;;,'.........',;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,::;,'...,loollol,,,.,;:;,;oxxkkkkkl,cxx:;;,,;::oxxOKXX0olOXKOkxxdoooooooddddooooodollllllccclcclokXWWWWWWWWWWWNXOlcodoodkxk00OOOOOOOkdxkkxlll;'.',:dxxdlllllooodo'........   .   ....                  .,;;;;;;;;;;;,,,,,,,''''''......" \
";;:::::ccllc:;,','.....'''''''''''''.............''''..................''... .looooooc;,''';cccdkkkkkOOxdxkdccc:lodx00KXNN0odKX0xdooooooodxxxxdddodddoooooocclcc:::;;;:oKWMMMMMMMMMWKOKK0XKkk0KKKK000000OOkkxddol;...'':xkkdollllodddo'.......... .        ..''.......      .;;;;;;;;;;;;;;;,,,,,,,'''''''''" \
":::::::clooolc,':l:;,.,loooooooollooccc,'';;;:clooooollc:cll;','..;;,,,c:....cxxkxxdddl:;:cccdxxolcoO0OOOkOOoldolxOKK0KXN0ldXN0xdooloddoodkxxkxdddddddddddolodolcc:;;;;:dXMMMMMWWWWN00XXXX0xk0KXXKKKKKK0000kdxkdl;'';;;cxkkdolllloddxo'.........   ..  .....';;,'......     .;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,," \
";'....':lodooc,.;lo:,',oxxxddxxxddxkxlc;:loxxxxkOOOOOkkdodkkoc:;;clccclxl'.;dOOOOOOo;,;:,,okkkkd:.'l00OkO000dldocokKKK0Kk:oXXOdooddoodxkkkOOkkkxxxkkxxxxxxdoooolcccc;;;ldkXWMMMNXXXK00000Okk000XXKKKKKKK000Oxo;;lc;;c:;lkkkdoollooddxo'.........   ......'',;::,.....'..    .;::;;::::;;;;;;;;;;;;;;;;;;;;;;" \
":. ...,lddxddo::looc,';dkkkkkkkkkkkkxoodddlclookOOOO0OOOxkOOdllol:::;,;oxllxO00000Oo,.':llokOOOkxdk0Kkco0KKKOkkk0OloOxlkkkK0xooooddxk0KXXXXXKK00OOOOOO0OOkxooolllcc::::::coOKNMMMMMMWWWWWWWNNK0KXXXXXXKKK000dcllcc;'cllxkkkxooooodddxo'.......... .',''''';:cc;'....''.     ';::::::::::;;;;;;;;;;;;;;;;;;;:" \
"l'....:dxxkxddddol:;;;:dOkkkkkkkkkkOOkkkkkdxkkdk000000KK0000xl:cooc:::cd00000K00000d;';coldOKOO00KKKkc:kXXXK0K00XXkodxd0WWKkdoloxOKXNNNNNNNNNNNXXXXKKKKKK0Okxxdoolccc:;;;;;;cdXMMMMMMMMMMMMWWWNWWNNNXXXXKKK0dcdo;';c:,,lOOOxooooddddxo'.......    .,:;;;;;:cc:;,'..';,..    '::::::::::::::;;;;;;::;;;::::::" \
"l,...:lllooolccll;,:lc:oddddoodddddxkxxdodOOOxodkkOOOOOOkkkxdooodddkxoldO00KK0O0000x;':oxkK0xolxxlc:,;kKXXXK000K0OOxdoxXWWXOdox0XNWWWNNNNNNNNNNNNNXXXXKKKK0000Okxdoolc:;;,,,,:kWMMMMMMMMMMMWWWWWWWNNNXXXXKKKxlc:;,::,,:dOOOxddooddddxl........ .  ..;;,,;::cc:;,,'',;,'.   .’:::::::::::::::::::::::::::::::" \
"o:,';c:;:ccc::ldkdc::;;::::cllooollllollcoOOddollldxodxxdoccodxxxddddolloxk00xlokxdxxxdlkK0xl:cdl'.'';clllllccccc:::::clodkxx0NWWWWWWNNNNWWWWNNNNNNXXXKKK00000OOkxdoollc:;,'',cx0OOkkkkkkkkxxxxxxxxxdddddddolllclcc:;::cllloddooddddxl.......... ..,;:::;:c:::;;,'...'.    .':::::::::::::::::::::::::::::::" \
"kkxxxdc:cllc::cdkdooollol::lkOxddoccloc:cx00xdolloxxddd0KkoollooolloddolloxO0dooooodloOKKKxok000d;;;,'',,;,,,,;;;;,,,,;,,cdkKWMMMWWWWWWWWWWWWWNNNNNXXXKKKKK000OOkxdoollccc:;,,colcc::cccccc::::::::::::::::cccccccc:::;,,',lddddddddxl......';;,..:llllcc::::::;,......     ':::::::::::::::::::::::::::::::" \
"kOOkOdc::c:,,,;lollooc;;;;;;oxdoolc:::;;:looodooolcccldO0kxkxxOkoc:coolcc;cO0kkkkkxOxoONXx,;0NXKxcclccc:,.''''''''''',:lodx0NWMMMMMWWWWWWWWWWNNXXXXXXKKKKK000OOOkxdoollcccc:;;oOkxxxxxxxxxxxxxxxxdoloddc;:ldkOOOOOkkxdc:;;:oddddddddxl......';cc,'lxoloc:::;;;,,'.....      ';::::::::::::::::::::::::::::::" \
"kOOOOd,,:;,,,'',,,,,;:::;,,;coooolc;;;;,,;c;,:cc:;,lk0KXXXXXXXXK000OOOOOOkO0KK000dcolcool,,kXXXKkodxdxOd'.........';cdkO000KNWWMMMWWWWWWWWWNNNXXXXXKKK000000OOkkxddooollllcc::xNWWWWWWMWWWWWWWWWXkc::cl;.,dXWMMMMMMWWWKxoooddddddddxxl......'ldl';oc..cc;;::;,'......       ':::::::::::::::::::::::::::::::" \
"OOOOOx;,::;;;,,,,;;:coxxxdlloddddoocc::;:::;',cllodONMMMMMMMMMMMMMMMMMMMMMMMMMMMMOcl:,;cloOXXXXXkdkOOO0x'......':ldkOOOO0KXNNNWWWWWWWWWWWWWNNNXXXKKKK0000000OOkxxdoooolllllc:;dNMMMMMMMMMMMMMMW0l,'.......lXMMMMMMMMMMXOxxxxddddddddxc.......,,'.,:. .;:;;::;,... ..        ':::::::::::::::::::::::::::::::" \
"O0000x,'::;;;,'',,,;codxkkxxddxxddxxo:;;;;;,';loodxkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMOlkKKXXXXXXNNNXOdO000Kx'..',:oxxkkkOOO00KXNWWWWWWWWWWWWWWWWWNNXXKKKKKKKK000OOkkxddooollllllc:lKMMMMMMMMMMMMMMNl.......  .lXMMMMMMMMMMXOkkxxxddddddxxl',::;.         .';;;;;'....           ':::::c:::::::::::::::::::::::::" \
"00000x;,:::;,,''..';looooxkOkkOOkO00d:;;;;;,',,,,,,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMM0lONXXNNNNNNNNXOxOK000kc:ldxxxkkkkkOOOO0KXNNNWWWWWWWWWWWWWNNNXXKKKKKKKKKK00OOkkxxdooolllllcc:c0NNNNNNNNNNNNNNXl.      ..'kWMMMMMMMMMMN0OOkxddddddk00d:col:.         .'''.... ..        ... ':::::ccc:::::::::::::::::::::::" \
"0000Kx;;ccc::;,'''':odxdodxkOOkkOOOxl:;;;;;,',,,,;;cOWMMMMMMMMMMMMMMMMMMMMMMMMMMM0oOXXXNNNNXNKkOOxOKKK00kkkkkkkkkkkOOOO00XXXNNNWWWWWWWWWNNXXXXKKK0KKKKKKK00OOkkxxxddoollllc:c:clc::::::::::::cc'.     ..':OWWMMMMMMMMMN000OxdddddOXX0Oxl::,.     .,..,:'.         ..     ',.,::::::cc:::::::::::::::::::::::" \
"O0000x;cddxddddl::;;;cdkkxxkkkkkOkdoc:;;;;:,',,;okOOKWMMMMMMMMMMMMMMMMMMMMMMMMMMM0oOXKXXK0XXXXKKOxOK0KK0OOOOkkkkkOOOOO000KXXNNNWWWWNXXKK0OOOkO0000000000OOkkxxdddddddolllc::c:lO00000000000Ol'.  ...,;;''lXWWMMMMMMMMMNKKK0xddddONNKkOOo:;'      ;l.....         .;:'     .;::::::::::::::::::::::::::::::::" \
"xOOOOx::ooodxkdc:;;,'.,:lllodxkOkdol:;;;;;;,',,,:x0O0WMMMMMMMMMMMMMMMMMMMMMMMMMMM0oolcoocldONWNXOdO00KK0OOOkkkkkOOOOOOOkOKKK000Okxdollc::;;;;coxkkkkkkkxxdolc:;,,,;:cccccccc::oXWWWWWWWWWWMXc.''',,:lo:..ckkdxkKWWXOxdodkKKxodoxKXK0kkkdc;.     .;;..''        ...,:;.    .',;::::::::::::::::::::::::::::::" \
"xdoxOklclloddl:;;;,'...',,;;:clkkolc;;;,,;;,',,,,:llxNMMMMMMMMMMMMMMMMMMMMMMMMMMM0ooccc:c:.lXWNXOdO000000OkkkkOOOOOOOOd,:dxo'.':::;,,,,'''...',;coxxxdoolc:;,'....'',,,;;:ccc:dXWWWWWWWWWNKOc;;,,,,'''...''....,x0ko:'. .l0xoxkOkOOkxddo:.      .,;.....     ..',',,,'     .;ccc::::::::::::::::::::::::::::" \
"xdlx00xool::c:;,;,'....'',,;::ckklc:,',,,,,'.,,,,;::dXMMMMMMMMMMMMMMMMMMMMMMMMMMWOok0Okxd,'kNNNXkdk00000OOkkkkkkkkOOOOxl:;xk;.oOdc;,,;,'..'''''''..','''..................',,,oKWWWWWWWWXo:;,'..............    .lxol:.  'dkk00K0xdxxooo,      .cooc;,,;;;,',:c:::;:od'    'lc,'::::::::::::::::::::::::::::" \
"kOkxOOdlllc;c:,';,'....'',,;;::dkl::,,,,,,,'.,,,:clldKWMMMMMMMMMMMMMMMMMMMMMMMMMMkcxOkl,,,lKNNNXkdk0O000OOOkkkkkOOOOOOxk0KKXd;kKkdolllc'.';,';loo, .'.   .......  ..........  .:xXWWWWWWXo'..        ....       .;ccl;. .;OXXK000Odlcccc'      'ldl,',:ccloooooollccll,    'l,.,c:::::::::::::::::::::::::;;" \
"k00kddollooclc;;;;'..,,,;;;;;;;:lc;;,,,,,,;,,,;;,,,,;oO000000000000000000000OO00Ol:kOkxddkKNWWWXkdkOOOOOOkkkkkkkkOOOOOolk0KNO:xXKKK0Oxdollllodxkd,;kOo:..',,'','...'....',;' ..,,cdxxdxONx.                        .'...;ONX000OOOkc.';;.     .;:c;;;;:llloolloc:,,,,;'    ,;';llc:::::::::::::::::::::::::;" \
"O000xoodkOxoddodol::xOxdddddddddddddddooooddddooooooooooooooooooooololllooocccldkxxKNXKOO0KXXNNXxokOOOOOkkxxkkkkkkkkOOxkK0OXXooKK0KK0OkkxxxxkO0kcc0N0dl,.';;;;:::::::;;,;:c,.':;,':ll:ckK:                           ..,cxkdclododd:..',.    'oxkxooddoodoodloxxo:,..,,.  .;c;;;,;::::::::::::::::::::;::;;;" \
"O00OxxxkOkocooloollkX0xxxxxxxxxxxxxxxxxxxxxxxxxddddddddxxdddxxdddxdoxxdoodddodxkO00Kxd0KXNXK00KKxoxOkOOkxxxxxxxxxkkkkOO0Odd0N0ldOOO0000OOOO0KKOcl0NKkol:..;::ccccccccc:::::'.;:c;,dNWWWMNc                       ....  .'',,;::ccod:..'.    'oxOOkkdoodxxxkkxxxdlcc:,,'. .,:;'. .,::::::::::::::::::::;;;;;;" \
"k0OkkOkxxxdoddooodk0KOxddddddddddddddddddddddddddddddddddddddddddddooxxdxkOxodkOOO0k:;dOX0ddocx0xlxkkkkkxxxxxxxxxkkkkk0KkdOXNNKxddodddxxxxxxxo:lKNNKxolc,..;clloooolllc:::'',,,:;;kWWWWMMx.                      ......;c;,;lddoccoc....   .cdkOOOxdxdxkloOkxkd,.;ll:,.. ,:,.   .;:::::::::::::;;:::::;;;;;;" \
"kkkkkxxdolccoddddddxkxxxdddddddddddddddddddddddddxxxddddddddddddddxxdoodxxkkxxkkxodOdlodKOclOOk0xlxkkkkkkxxxxxxxxkkkkkOKKKXXXXNNXKOkxddoollolokKXXXKkolc:,..,;::cclccc:;,',;:;',,lXWWWMWW0,                       ...;dOko:..';,.....     .:dkOO0kddl;ox:cOd;,.  .coc;' ...     .;::::::::::::::::;;;;;;;;;;" \
"kOOkxkkdodooolcloodddddxxxxxxxxxxxxxxdddddddddddddddddddddddddddddddoloO0kxxdxO00kk0xox0XXKKKKK0dldkxkkkxxxxxxxxxdddddx0XNNXXXXXXXXK00OOkkxddOOkkkkxoc::cc:;,;;;::::;;;;;::::;,,c0WNWWNKXXl                       ...:llc,........        'dkOOk0d.....,..:' .:.  ,olc,         .;::::::::::::;;;;;;;;;;;;;;" \
"kOOOOkxddxkkxdolldolooxxxxxxxxxxxxxxxxxxxdddddxddddddddddddddddddddxdoxOKKOxxxOXXOkOOKXNKxodxk00dldkxxxkkkkxdoolcc:::cclkKXK0KXXXXKK0OOkxdddxdc,:cc:;,''.';;;clloooooollcc::;::;;:cclOKkONk.                       .,codolc:;..          .ldxOOOKx.     .,,;:cd:. ,olc,  ...    .,:::::::::;;;;;;;;;;;;;;;;;" \
"kkkkkxooodxxxxdlcoc:loxkxxxxxxxxxxxxxxxxxxddddxdddddddddddddddddddxxdoodkO00OOOkxlddoox00kc:okK0dcdxxxxxkxolc:::cccldkkolddddOKKXXKK0OkkkkO00Okxdolccc::;;;;:clooodoollcc:;;;:coc;;;ck0OKWX;                       ..cxkkkkdl:'..        .;cclkk00;   .cdkkkkkkxocoko:. .',......,::::::::;;;;;;;;;;;;;;;;;;" \
"kkkxkdllc:::cloocl:;clddddxxxdxxxxxxxxxxxxxddddddddddddddddddddddddoddloxkddddooocc:'';okdkdcodkdldxxxxoll;';;;::cokOOOkollookKKKKK0OOOO00KKXXXXKOxddoollccccclloooollcc::;,;lxKKKKKK0OOXWWx.                     ...o0koldxdoo;...       ...':ox0k;.;dkkkOOOkkkxdddc,. .','';:;;;::::::;:;;;;;;;;;;;;;;;;;;" \
"::;,,,,,'...,lxdclc::loddddddddddddddddddxxddddddddddddddddddddddddkOOxxk0Okkkxdxooc,'',c::loolxocdxdxx:.....',;::okOOOOkxoodOKKKKK00000OOKK0Okxxdddlccccccccccloolllc::::odx0KXXKKK0OkONMMO.                    .. .;odc:x0Okkdc,.       ....';lxkkxddkkkOOOkxdooo:;.   ..'''..';:::::;;;;;;;;;;;;;;;;;;;;;" \
",''..........cddllllodooooddddddddddddddddxdddddddddddddddddddddddxkkxoodkOxddoolcc:'...:ll:cookocdxddd;   .''';:;cdkkOOOOkxdkKXKKKKKK0kdooooolllcc:;;,,,,',,;:loollcc:::cxO0KKKKKKK0OOKWWNd.                    ......;lx0K000Oxl'    .. .''',cc:lxxdooxxxxxxlllc;...   ..'''...;:::;;;;;;;;;;;;;;;;;;;;;;;" \
"l,'..........,ccccloxxolooooooooddddddddddddddddddddddddddddddddddx00kocclol:cl::::;..':lcc;:ldkocddddd;  .';,,;:;;;:lxOOkkkdx0XKXXXXXK00000000Oxdoolllcc:;;;;cloollcc:::lkOOKKKKKKK0O0XWWWx.                     .......:x0XKOo;'.   .,,..'',:dd:',:clcllcodol:;'.''.  .';:cc:'.;:::;;;;;;;;;;;;;;;;;;;;;;;" \
";'''''''',',;::c:clooooooooooooooooooodddddddddddddddddddddddddddddoloocloxxdxxooll:;;;:loccxookocddddd;...',',;;;::,cxkkkkkkk0KKXXXXXXXXXXXKK0kdooooollllllooooollccc:::oOkO0KKKKKK0Okkxddc..                       ...  .cxo;'....  .':;;ll::odc,';oollllllcc:,',:c.  ...';lc,,;:;;;;;;;;;;;;;;;;;;;;;;;,," \
"cccc:;,,'.';clll::ll:,,,,,,:lllllllooooooodoodddddddddddddoodddddddclOOxOO000KKxocloocldollddddOlcodddd;''.',''';;:;:dkkkkkxkOO0KKKXXXXXXNNXXXKK00OOkxxxddddooolllcc::::cxOkO0KKKKK0kol;...                              .'..'',,,........',,,,:ol::clolloddoodoc:cc,.     ..';,;::;;;;;;;;;;;;;;;;;;;;;;,,," \
"ddol:,'....,:cc;';lc.......;clllllllllloooooooodddoodooooooooddoddxdld0Ooclddxdll:lkooddxccoc:lklcodddo:,,.''''.,::,:dxkkkxxkkk0000KKKXXXNNNNNNXXKK00OOOkkxddolllcc::::cdOOkO0000000Oxd:.                                'l,...',;;,'.......';,;oxolcccc:::ccccccc:;. .......';;:::;;;;;;;;;;;;;;;;;;;;;,,,," \
".....      'clc,.,l:.......;cllllllllllloooooooooooooooooooooooodoooccloxOkkxdolddxdoooodc;c::dkl:odoooc;'.''''..;::cdkkkxddxxkKX0kkO00KXXNNNNXXK000OOOkkxdoollcc:::;::lkOkxk0000000000c                                .ok,....,;;;;,'.....''.;l:;::cool:;;;:::;,'.........,;:;:::;;;;;;;;;;;;;,;;;,,,,,,,," \
"           'ccc,.,c:. .....;clclllllllllooooloooooooooooooooooooooox0OxdkKKKK0kx0Kkdlcoooooc::okc:oooooc,'..,'...';:ldxddddxxkk0XX0kddxkO0KKKKK0Okkkkxxdoolccc:::;;;;ldoxkxdkOO0000O00Ol.    .'.             ..         cXO,....,;;;;;;,.......,:::coddolc;,;:cc:,,'.';,....,;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,," \
"           ':c:'.,c;.  ....;ccclllllllllloolloooooooooooooooooooooloddxxk000OkkO0kkxldd:cl:cdo:dc:ooool,.   ... ..,;:loddxxxxxx0XXXKOxddoddxxxxxddddolccc:::;;;;;;:::lo,.''.',,,,,,,,,,..     ..             ..        .xWk,...',;;:l:;;'.......'''':oooc::;;:c:;::,',;,.. .,:;;;;;;;;;;;;;;;;;,,,,,,,,,,,,," \
"           ':::'.,c;.   ...,ccccccllllllllllllooolllllooollloooooolooolclxxddlcododccdl,cdl;cccdc:lolol'        .'',:ldddddddocxXXXXKOkkxdollccc::::;;;,,,,,,;;;:::::dd,.'''''''''''''''..    ..                       :KWk,...',,;::',:,...   .,,,,;loc:;;:::c:,,,,,.......,;::;;;;;;;;;;;;;;;,,,,,,,,,,,,," \
"           '::;..':;.   ...;:ccccccllllllllllllllllllllllllllloooloddolodxollccllodoodlcoxocxxdxc:lolll.          .............oNXXXXKOOkkxxdolc;;,,,,,,;;;::::::::::ll:loodddxxxxxxxxxxo.   .c:.            .        .xWNk,...',;;'  ,:,...   ..,;:cllo:'.,::;,'....    ...,:;;;;;;;;;;;;;;;;;,,,,,,,,,,,,," \
"           ';;,..':;.   .'';:ccccccllllllllllllllllllllllllllllllllllcclkOxolloooxkdldk00kk0Kkdd::lollc'        .....''''''''.'xNXXXXXK0OOkkkxdolccc:cccc::::ccccc:::'.'oddddxkkOOO0000Kd.   'kx.           ...       .kWNx'...',;;lc,;;....    .',::,;c:,:lc;'..,;,'......',;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,," \
"           .;;,..':,    ..';:ccccccllllllllllllllllllllllllllllllloxdlokOxdolloooxkkO0kkx;,kKkxx::llllc,.........''',;;;:;;;;:dKNXXXXXXX0OOkkxxddoollllcccccccccccc::'  ,dkxkO00KKXXXXNXl.   ,0O'           ...       .xNNx'...,,;:kKd;'....     .;;,,::cool:..  .';:::;;,,',;:;;;;;;;;;;;;;;,,;,,,,,,,,,,,," \
"           .,,'..':,   ...';:ccccccccllllllllllllllllllllllllllllllooodOOdodxddl:cdkOOkOk;,k0kOx:;llc:;'.''......''',,;;;;;:oONNXXXXXXXXX0Okkxxddoollllcccccccccccc::;. .:O0KXNNWWWWWWWWd.   ,00'           ..  .     .lXNx'...,,;oXNKxc'... ..  .cdddddoolc:,.    .....';'.,;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,," \
"           .''.. ':,    ...,:cccccccccclllllllllllllllllllllllllll:;:cokkkkkxdlol;ld:;:d0koO0xkd;,:;,''...........''',,;:ldOXNNNXXXXXXXXXK0Okxxddoollccccccccccccc::::;'..oXWWWWMMMMMMMMx.   '00,          .........   c0Kd'..',,:ONXK0koc;. ....:dxddxkkkxolc:;,,''''',;;..,;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,'" \
"           .''.. ':,    ...',;;;;;;;;;;;::::::::::::::::::::::::::;,,''',,;;;;;cc',c:;,:odddddd:..'',,,'.........',,;cclOXNNNNNNXXXXXXXXXKK0Okxdoollcccccccccccccc::::::;,,cxKNWMMMMMMMMk.   'OO,          .........   :0Ko'..',,l0X0Okkxdl::clccllllloxkkkxdooooollllllc:'.,;;;;;;;;;;,,,,,,,,,,,,,,,,,,,''" \
"           .''.. ':,       .........''''''''''''''''..'''''''...''...........'''........'''''''...,,,,,'......''',;;ccckNNNNNNNNXXXXXXKKKKKK0Okxdoollcccccccccccc:::::::::;...,cdOKNMMWMk.   .kO'    .    ..',,'....    ,do'..',;dK0Okkxxddoooolc:;;;,;:cllllolllllllcc:c;..,;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,'" \
"           .''...':'       ..........''''''''''''''''''''''''''''''..'',,,,,,,''''',,,,,;;;:::;,'',,,,''''',,,...,',;;:xXNNNNNNNXXXXXKKKKKKK0Okkxddollcccccccccc::::::::::;.     ..,:okK0;   .xk'   ..   'xd;;;,'...      ....',:kK0Okkxdoolllcc:;;:::;;,,',;;;;;;;;;;;::;..,;;;;;;;;,,,,,,,,,,,,,,,,,,,,,''" \
"           .''...';'       ...........'''''''''''''''''''''''''''''''',,,,,,,,''',,,,,,;;,,;;;;,,',,,,;;;,,,'...','',,,l0NNNNNNNXXXKKKKKKKKK00Okxxdollllcccccccc::::::::::,.           .,'. .;00;  ..   .lNXo;;,....       ...',cO0OOkxxddollllllccccc;''';:::::::ccccccc:..,;;;;;,;;,,,,,,,,,,,,,,,,,,,,,,'" \
"           .''.. ';'       ....''''''''''''''''''''''''''''''''''''''',,,,,,,,,,,,,'...''..''',''';;::;'..'.. ..','',,,;dKNNNNNNNXXKKK0000000OOkxxdoolllllcccc::::::::::;,.                 .,dOd. .    ,OWWKl,....  ...   ...',lO0Okxxdoooollollccc:;'..',;:::cllllcccccc'.';;;,,,;;,,,,,,,,,,,,,,,,,,,,,,'" \
"..         .''.. ';.       ....'''''''''''''''''''''''''''''''''''''',,,,,,,,,,,,..           .',;;;,....'.. ...''''''',;xXNNNNNXXKKK000000OOkkxxddoolllllcccc:::::::::;,..                    ......  .cOKOc......  ,l'   ...',o0Okxdddoooooollcc:,''...';,;::cccccccc::c,.';;,,,,,,,,,,,,,,,,,,,,,,,,'''''" \
"           .''.. ';.       .....''''''''''''''''''''''''''''''''''',,,,,,;,,,,,,.          .',;;,,''....... .....'...'''',oKNNNNXXKKKK0K000OOkxxddoooolllllccc::::::;;;'..                        ..........    ..   'ko.  ...';xKOOkxddooollllc:;'....  .:;;::ccccccc::::,.',,,,,,,,,,,,,,,,,,,,,,,,,,'''''" \
"           .''.. ';.       .........'''''''''''''''''''''''''''''''''',,,,,,,,,'.      ..';;;,''''........  ....'..'''''..'ckXNNXXKKKKKKKK0OOkxxddoooooooolccccccc:;,,'..                            ......          ;Ol..:,..':k0OOkxdoollllcc:;'.       ,cccllc::ccc:;;;'.',,,,,,,,,,,,,,,,,,,,,,,,,''''''" \
"           .''.. ';.       .'..''''''''''''''''''''''''''''''''''''''',,,,,,,,,'.  ..',;:;,'...'''.......  ....'....'''.....'lOXXXXXXXXXXKK0Okxxddddddddddoollllcc:;,'..                                 .......    .c0x,.;'..':k0kkxddddolcc::;'.        .clcc:::cllc::;;..',,,,,,,,,,,,,,,,,,,,,,,,'''''''" \
"           .''.. ',.       .'''''''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,'',;;;;;;,....''''.. ....  .........'''.......'cx0XNXNNNXXXK0Okxxxxxkkkkkkxxddoollc:'..                                     ......  .;do' ..  .,x0kxxkkkdocc::;'.         .:lcc:cllllcc:;,..',,,,,,,,,,,,,,,,,,,,,,'''''''''" \
"           .,'.. .,.      ..'''''''''''''''''''''''''''''''''''''',,,,,,,,,,,;:::;;;;,,,,.....'''...  ..  .......................,cd0XNNXXXKK0OkkkO000000OOkkxxdl:'.                                            ...  ':,.......,xOkkkkxolcccc:,.          .;lccllllllcc:;'..',,,,,,,,,,,,',,,,,,,,'''''....'" \
"           .'''..',.     ..''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,;::;;;;,,'''............  ..  ..........................':lxk000000OO0KKXXXXK0Okdc;'.                                                 ....'...','.,x0Okkxollcccc:,.            'olccccclllc:;.  ..............................  " \
"           .,'',,,,.  ......''''''''''''',,,,,,,',,'',,,''''',,,,,,,,,,,,,,;:c:;,,''''..............  ..  ...............................',;:clooodddollc;,..                                                      ......';,,'l0Okxxxdooollc;.             .llcclcclllc:,.                        .,cl:..   " \
"           .,'....,'...........''''''''''',,'''''''''''',,,,,,,,,,,,,,,,,,;:c:;,,'..'''.............  ..  ...........................................                                                               ....',;,,,l0K0000Okxol:,.              .coccllllllc;,.                     .,lxO00Oxc'  " \
"          .',,'..','..............'''''''''''''''''''''''',,,,,'',,,,,,,,;::;,,''.....'.............  ..  .........................................                                                                  ..',;;,,,oKKKK00Okdc;,..              .:olcccllol:;,.   ..  .       .  ..;x0K000OkOOxl'" \
"          .'',,..,;;'........''''''''''''''''''''''''''''''',,,,,,,,,,,,;:c:,'''...................  ...   .................................................       .                                                  ..,;;;,:OXK000Okoc;,..               .,oollllllc:;,.   ................cOK000Okkkxxkkx" \
"     ... .....',;clo:........''''''''''''''''''''''''''''''''''',,,,,,,,::;,''''...................  ...   ................................................      ...                                                   .';;;ckXXK00Okdc,..                  .ldllllclc:;,.    ..............;kK0OOOOkkkxxxxx" \
"...'''.. .......,;;:,........''''''''''''''''''''''''''''''''''''',,,,,;:;,,''.....................  ...  .............................    ....... ......       ....                                                    .;;;o0OkOOOkd;'...                  .coc:::ccc;;,.   ...............:O00OOOOOOkkkkxx" \
";::;,.....'','...''...........''''''''''''''''''''''''''''',,,,,,,,,,,;::;,''......................  ...  ......................... ... ..   ............      .....                                                    .,;;dkdloddc;,,'.                    ;l:;;;;;,'','.  ...............,x0OOOOOOOOOkkkk" \
";;,'...  .',,,'...'...........'''''''''''''''''''''''','''',,,,,,,,,,,::;,'''......................  ...  ...........................           ........      .....                                                      ',cO0kdoolc:;;'.                    'ooc::;;,,,''.. ................,okkkOOOOOOOkkk" \
"''...    .';;,'.................''''''''''''''''''''''''''',,,,,,,,,,;:;,,''.......................  ..   ..........................               ...       ......                                                      .;dK0kxolllccc,.                    .llc:::::::;;'. ................'lxddxkkOOOkkxx" \
",..   ....';;,'.................''''''''''''''''''''''''',,,,,,,,,,,,;:;,'.................... ....   .  .... ...........  .........      ..       ..        .....                                                       .;x0Okxdollllc'                     .:l::;;;;;;;,.. .............':okOxdxxxddxxkkkk" \
"'.........',,,'''.................'''''''''''''''''''''',,,,,,,,,,,,,;;,''.........................  ..  .... ........... ..........              .........',;clooc;;ccllc::;;,,,,'.......                                ;O0Okxdoocc:'                       ,:::::;;;;;,'.  ..........,okOdc,.'okkkxdddddx" \
"..........',,,''''..............''''''''''''''''''''','',,,,,,,,,,,,;:;,'''.................... ...      ......................''',;::;;;:::ccccclooddddoldO0KXXKOxdx00KKK0OOOkkkkkxxxdddolccc:;,;:;.                     ;O0kkxdolc:'                         ..';;;:;;;,'.    .......:xdc'     .cdkkkkxxdd" \
".........'',,,'''.................'''''''''''''''''''''',,,,,,,,,,,,;;,,'...................... ...     ........,,;;:cloddooxkkOOO0KK0OOOO0000OOkkOOOO0kddk0KKXXKOxdk00KKKK00OOOkOOkkkkkkkkkkkkxxO0Ol.                    ;OOkxdolc:;.                             .,;:;;,..   .......cl'       ...;cdxkkkkk" \
"........'''''''''..................'''''''''''''''''''',,,,,,,,,,,,,;;,'.................  ....  .     .';:cldkOO00O0000OOkO0000000KKKOkkO0000OOkkOO0K0OxxO00KXK0xox000000K0OkOOxkOOkkxxkkxkkkkxxkO0d'                    ,kOkxdlc:;'                               ..',,,.. .......';'        ......';lddxk" \
"'''.....''''''''''.................''''''''''''''''''''',,,,,,,,,,,,;,,'.................    .      .;coO0K00KXXK00O000K0OkOO0000O0KKKOOkkO0000kxxOOO00OxxkO0KKKkdok000000K0OkkkkkOOOxddxxxxkxxdxkO0x'                    .xOxdol:;,.                                  .....    ...;l'        ..........,:ld" \
"'''''''''''''''''......................'''''''''''''''''',,,,,,,,,,;;,'...................       . .;odkK000OXNX00OO00O00OkkkOOO0OOO00OOkxk000OkxxkOOOkkxxkOOKK0xlokOO0OOO00OkkkxxkOOxddxxxxdxdddxkOk,                    .oOxdlc;,.                                         . ...,d:        ..............." \
"''''''''''''''''.......................''''''''''''''''''',,,,,,,,,;,''...................     .':c;;okOKKKOOXXK0OkkOO00OOkxxkOOOkkkkOOOkxkkkOkxdoxOOkkkxxkkOKKOdldkOOOkkOOOkdxkkxxkxxxddxddddolldkOx,                    .lkxoc:;,.                                         ... .lc.        . ......       " \
"''''''''''''''''''....................'''''''''''''''''''''''''''',;;'..................       'oxdc;lkOO0KO0XKOOOOkkOOOkkxdxxkkOOkkkOOOkxxkkkxdodxkOkkkxdxkOOxoc:ldxxdddxxxdddddoddxdxxxxxdddolldkxd,                     ckdlc;;,.                                            .,xo'.                 ..',;" \
"''''''''''''''''''''...................''''''''''''''''''''''''''',;;'...................       ;ooc;cdkO00kO00kOOxdoxOOkxddkOOO00kxxxxxdlcllc:;,,,,,,,,'...''..   ...................'''',,,,;;:cloo,                     :kdl:;,.                                              ;xkxlc;'...,,'...',;cldxkkx" \
"''''''''''''''''''''...................''''''''''''''''''''''''''';;,'................          .:lc;;oxxkkdx0Okkkxdodxxoc:::c::;,'.......                 ....                                   ...                      :xdl:;'.                                              ;xkdxxkkxxxkkkkkkkkkkkkkkkk" \
"'''''''''''''''''''.................''''''''''''''''''''''''''''',;;,'...............            'lc;;lxkOdlodoc:;,''.....                       ..........',,... ....    .............          .                         ,ddc;'.                                               ;dkxkOOkkkkkkkkkkkkkxkkkkkO" \
"'''''''''''''''''''................'''''''''''''''''''''''''''''',;;''.............              .;:;',::;.....      ......................................,;,'.  ....           ............. ...                         .odc,.                                                .;okkkkOOOkkkkkkOOOOkkkkkOO" \
"''''''''''''''''''................''''''''''''''''''''''''''''''';;,''...............             .,.       ... ......','...'''''''.......................',;,..  ....                                                     .dkc,..                                                 .cxkkkkkkkkkkkkkkOkkkkkOk" \
"'''''''''''''''''''............''''''''''''''''''''''''''''''''',;;,'...................          .'.   .  ..'...'''',;;,'''''''''........................,;;'..  ....                                                     .lOo;'.                                                   ,oxkxkxxkkkkkkkkkkkkkkk" \
"'''''''''''''''''.............'''''''''''''''''''''''''''''''''',;,,'................  .               .....',....'',,;;,'''''''''.......... ............',;,..  ....                                                       ,do,.                                                .    .:dxxxxkkkkkkOOkkkkkkk" \
"'''''''''''''''''...........''''''''''''''''.....'''''''''''''',,;,''................                . .....',....'',;:;,''''''''........... ...........'';;'..  ....                                                       .;:.                                                       .;xxdxkkkkkkkkkkkkOOk"


c = 0
colors = ['\033[97m','\033[96m','\033[95m','\033[94m','\033[93m','\033[92m','\033[91m']
while 1:
    print("\033[1m"+colors[c]+ascii_art)
    c += 1
    if c == len(colors):
        c = 0
    ts(0.1)
    os.system('clear')
